import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedVentyourfeelingsfreelyWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedRectangle681Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedVectorWidget1368.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedGroup338Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedRectangle491Widget66.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedGroup298Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedGroup404Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedGroup299Widget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedLight1Widget67.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget1/generated/GeneratedEverexperiencedthetimewhenyouwantedtoventyourfeelingsto1.dart';

/* Frame onboarding screen-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingscreen1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 9612.000301361084,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1121.0,
                              top: 9592.0,
                              right: null,
                              bottom: null,
                              width: 20.000886917114258,
                              height: 20.000301361083984,
                              child: GeneratedVectorWidget1368(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 570.0,
                              right: null,
                              bottom: null,
                              width: 297.0,
                              height: 38.0,
                              child: GeneratedVentyourfeelingsfreelyWidget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 358.0,
                              height: 122.0,
                              child:
                                  GeneratedEverexperiencedthetimewhenyouwantedtoventyourfeelingsto1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 409.0,
                              height: 291.0,
                              child: GeneratedGroup299Widget13(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 252.0,
                              height: 59.0,
                              child: GeneratedGroup298Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -3.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedLight1Widget67(),
                            ),
                            Positioned(
                              left: 164.0,
                              top: 792.2903442382812,
                              right: null,
                              bottom: null,
                              width: 99.29032135009766,
                              height: 10.290352821350098,
                              child: GeneratedGroup338Widget6(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 32.0,
                              child: GeneratedGroup404Widget8(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 419.0,
                              height: 332.0,
                              child: GeneratedRectangle681Widget(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 5.0,
                              child: GeneratedRectangle491Widget66(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
