import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedReactionWidget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedReactionWidget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedNavWidget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedHWidget51.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedEllipse2Widget43.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedTitle4Widget27.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedTitleWidget126.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedFrame1Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedGroup3Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedRectangle7Widget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedFrame2Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedQuoteWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedTitle2Widget67.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedTitle3Widget57.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedReactionWidget15.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedHiWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget3/generated/GeneratedReactionafterWidget12.dart';

/* Frame R2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedR2Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 44.0,
                child: GeneratedHWidget51(),
              ),
              Positioned(
                left: 16.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget126(),
              ),
              Positioned(
                left: 16.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 112.0,
                child: GeneratedRectangle7Widget16(),
              ),
              Positioned(
                left: 16.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitle2Widget67(),
              ),
              Positioned(
                left: 16.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 33.0,
                child: GeneratedTitle3Widget57(),
              ),
              Positioned(
                left: 16.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitle4Widget27(),
              ),
              Positioned(
                left: 16.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 398.0,
                height: 112.0,
                child: GeneratedFrame1Widget7(),
              ),
              Positioned(
                left: 16.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 398.0,
                height: 112.0,
                child: GeneratedFrame2Widget7(),
              ),
              Positioned(
                left: 16.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 56.0,
                child: GeneratedQuoteWidget7(),
              ),
              Positioned(
                left: 293.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedHiWidget7(),
              ),
              Positioned(
                left: 65.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 60.0,
                child: GeneratedReactionWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget34(),
              ),
              Positioned(
                left: 49.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget43(),
              ),
              Positioned(
                left: 65.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 54.0,
                child: GeneratedReactionafterWidget12(),
              ),
              Positioned(
                left: 84.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 44.0,
                child: GeneratedReactionWidget14(),
              ),
              Positioned(
                left: 118.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 18.0,
                child: GeneratedReactionWidget15(),
              ),
              Positioned(
                left: 279.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 54.0,
                child: GeneratedGroup3Widget5(),
              )
            ]),
      ),
    ));
  }
}
