import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedCrisishelplinesWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedFrame68Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedSelectCountryWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedLight1Widget61.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedLine22Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedRectangle474Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/Generated3Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedIfyouarefeelingsuicidalorhavingthoughtsofselfharmplease.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedVectorWidget627.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedMyanmarWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedGroup482Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedRectangle490Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomecrisishelplinewidget/generated/GeneratedCrisisHelplineWidget1.dart';

/* Frame Home/ crisis helpline
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomecrisishelplineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget61(),
            ),
            Positioned(
              left: 385.0,
              top: 57.0,
              right: null,
              bottom: null,
              width: 10.0,
              height: 14.0,
              child: Generated3Widget4(),
            ),
            Positioned(
              left: 123.0,
              top: 132.0,
              right: null,
              bottom: null,
              width: 184.0,
              height: 38.0,
              child: GeneratedCrisishelplinesWidget(),
            ),
            Positioned(
              left: 146.0,
              top: 342.0,
              right: null,
              bottom: null,
              width: 135.0,
              height: 29.0,
              child: GeneratedSelectCountryWidget(),
            ),
            Positioned(
              left: 22.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 386.0,
              height: 151.0,
              child:
                  GeneratedIfyouarefeelingsuicidalorhavingthoughtsofselfharmplease(),
            ),
            Positioned(
              left: 64.0,
              top: 384.0,
              right: null,
              bottom: null,
              width: 300.0,
              height: 46.0,
              child: GeneratedRectangle474Widget5(),
            ),
            Positioned(
              left: 84.0,
              top: 395.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 29.0,
              child: GeneratedMyanmarWidget(),
            ),
            Positioned(
              left: 331.0,
              top: 403.0,
              right: null,
              bottom: null,
              width: 16.0,
              height: 8.0,
              child: GeneratedVectorWidget627(),
            ),
            Positioned(
              left: 146.0,
              top: 914.0,
              right: null,
              bottom: null,
              width: 137.0,
              height: 6.0,
              child: GeneratedRectangle490Widget1(),
            ),
            Positioned(
              left: 19.0,
              top: 450.0,
              right: null,
              bottom: null,
              width: 389.0,
              height: 448.0,
              child: GeneratedFrame68Widget1(),
            ),
            Positioned(
              left: 128.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 175.0,
              height: 38.0,
              child: GeneratedCrisisHelplineWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 1.0,
              child: GeneratedLine22Widget3(),
            ),
            Positioned(
              left: 20.0,
              top: 59.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 29.0,
              child: GeneratedGroup482Widget8(),
            )
          ]),
    ));
  }
}
