import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatednickwidget1/generated/GeneratedLogoWidget11.dart';
import 'package:flutterapp/thoughtspotapp/generatednickwidget1/generated/GeneratedButtoWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatednickwidget1/generated/GeneratedNextWidget21.dart';
import 'package:flutterapp/thoughtspotapp/generatednickwidget1/generated/GeneratedTitleWidget128.dart';
import 'package:flutterapp/thoughtspotapp/generatednickwidget1/generated/GeneratedTitleWidget129.dart';

/* Frame Nick
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNickWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 139, 216),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 44.0,
                child: GeneratedTitleWidget128(),
              ),
              Positioned(
                left: 16.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget129(),
              ),
              Positioned(
                left: 171.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 71.0,
                child: GeneratedLogoWidget11(),
              ),
              Positioned(
                left: 16.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 89.0,
                child: GeneratedButtoWidget3(),
              ),
              Positioned(
                left: 309.0,
                top: 832.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 35.0,
                child: GeneratedNextWidget21(),
              )
            ]),
      ),
    ));
  }
}
