import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedLight1Widget41.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedExpertsWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedRectangle491Widget43.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedGroup173Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedGroup12Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedGroup65Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedGroup386Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedEllipse93Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedRectangle535Widget77.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedGroup174Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedClinicalPyschologistWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedAboutmeWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedDrZhongAngelaWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedRectangle330Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedRectangle86Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedVectorWidget269.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedNicetomeeteevryoneMynameisDrZhongAngelaIamagraduatefrom.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts5widget/generated/GeneratedBookasessionWidget3.dart';

/* Frame experts-5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 213, 234, 240),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget77(),
              ),
              Positioned(
                left: 147.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 29.0,
                child: GeneratedBookasessionWidget3(),
              ),
              Positioned(
                left: -130.0,
                top: -162.0,
                right: null,
                bottom: null,
                width: 697.0,
                height: 697.0,
                child: GeneratedEllipse93Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget41(),
              ),
              Positioned(
                left: 31.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedVectorWidget269(),
              ),
              Positioned(
                left: 170.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 41.0,
                child: GeneratedExpertsWidget7(),
              ),
              Positioned(
                left: 386.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup65Widget2(),
              ),
              Positioned(
                left: 141.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 23.0,
                child: GeneratedClinicalPyschologistWidget4(),
              ),
              Positioned(
                left: 122.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 183.9058837890625,
                height: 18.0,
                child: GeneratedGroup12Widget4(),
              ),
              Positioned(
                left: 156.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedGroup174Widget2(),
              ),
              Positioned(
                left: 292.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedGroup386Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedGroup173Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 360.0,
                child: GeneratedRectangle330Widget2(),
              ),
              Positioned(
                left: 139.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedRectangle86Widget3(),
              ),
              Positioned(
                left: 112.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 38.0,
                child: GeneratedDrZhongAngelaWidget4(),
              ),
              Positioned(
                left: 40.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 140.0,
                child:
                    GeneratedNicetomeeteevryoneMynameisDrZhongAngelaIamagraduatefrom(),
              ),
              Positioned(
                left: 40.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 29.0,
                child: GeneratedAboutmeWidget3(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget43(),
              )
            ]),
      ),
    ));
  }
}
