import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedEllipse2Widget38.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedFrameWidget194.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedFrame6Widget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedTitle6Widget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedTitle7Widget21.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedRectangle13Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedNavWidget29.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedTitle8Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedHWidget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedTitle5Widget21.dart';
import 'package:flutterapp/thoughtspotapp/generatedsharesomethwidget1/generated/GeneratedRectangle14Widget7.dart';

/* Frame Share Someth
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedShareSomethWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 225, 225),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 652.0,
                child: GeneratedFrame6Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget29(),
              ),
              Positioned(
                left: 207.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget38(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 228.0,
                child: GeneratedRectangle14Widget7(),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget44(),
              ),
              Positioned(
                left: 16.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 234.0,
                child: GeneratedRectangle13Widget7(),
              ),
              Positioned(
                left: 29.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 161.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 42.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 30.0,
                child: GeneratedTitle5Widget21(),
              ),
              Positioned(
                left: 49.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 23.0,
                child: GeneratedTitle8Widget8(),
              ),
              Positioned(
                left: 317.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 26.0,
                child: GeneratedTitle7Widget21(),
              ),
              Positioned(
                left: 358.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 33.0,
                child: GeneratedTitle6Widget14(),
              ),
              Positioned(
                left: 374.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget194(),
              )
            ]),
      ),
    ));
  }
}
