import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget86.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedRectangle8Widget25.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget82.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedNavWidget22.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedRectangle16Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget89.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget83.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedEllipse2Widget26.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget85.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget84.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedGroup7Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedHWidget36.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedTitleWidget87.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergency2widget1/generated/GeneratedECWidget3.dart';

/* Frame Emergency 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmergency2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget36(),
              ),
              Positioned(
                left: 257.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 173.0,
                child: GeneratedRectangle8Widget25(),
              ),
              Positioned(
                left: 16.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget82(),
              ),
              Positioned(
                left: 16.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget83(),
              ),
              Positioned(
                left: 16.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 33.0,
                child: GeneratedTitleWidget84(),
              ),
              Positioned(
                left: 16.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 86.0,
                child: GeneratedTitleWidget85(),
              ),
              Positioned(
                left: 16.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 37.0,
                child: GeneratedTitleWidget86(),
              ),
              Positioned(
                left: 16.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 72.0,
                child: GeneratedTitleWidget87(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget22(),
              ),
              Positioned(
                left: 286.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget26(),
              ),
              Positioned(
                left: 215.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 104.0,
                child: GeneratedRectangle16Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 104.0,
                child: GeneratedGroup7Widget4(),
              ),
              Positioned(
                left: 259.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 33.0,
                child: GeneratedTitleWidget89(),
              ),
              Positioned(
                left: 55.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 154.0,
                child: GeneratedECWidget3(),
              )
            ]),
      ),
    ));
  }
}
