import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedDidntreceivetheOTPResendOTPWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedEddiethebanish69gmailcomWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedLight1Widget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedEnterOTPhereWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedGroup302Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedRectangle491Widget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedVectorWidget33.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedAnOTPissenttoyouremailaddressWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin2widget/generated/GeneratedGroup413Widget.dart';

/* Frame log in-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup302Widget1(),
              ),
              Positioned(
                left: 119.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 50.0,
                child: GeneratedDidntreceivetheOTPResendOTPWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 63.0,
                child: GeneratedGroup413Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 38.0,
                child: GeneratedEnterOTPhereWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 41.0,
                child: GeneratedEddiethebanish69gmailcomWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 32.0,
                child: GeneratedAnOTPissenttoyouremailaddressWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget14(),
              )
            ]),
      ),
    ));
  }
}
