import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedFrame73Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedIfyoudonthaveanaccountSignuphereWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedWhatsyouremailorusernameWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedEnterUnsernameWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedVectorWidget32.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedEnterpasswordWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedLogbackinWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedGroup299Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedEnteryourpasswordWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedGroup302Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedRectangle491Widget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedWelcomebackWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedLight1Widget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedlogin1widget/generated/GeneratedGroup301Widget1.dart';

/* Frame log in-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget32(),
              ),
              Positioned(
                left: 19.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 50.0,
                child: GeneratedWelcomebackWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 38.0,
                child: GeneratedLogbackinWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget12(),
              ),
              Positioned(
                left: 21.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 32.0,
                child: GeneratedWhatsyouremailorusernameWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 32.0,
                child: GeneratedEnteryourpasswordWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup301Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup299Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup302Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 24.0,
                child: GeneratedFrame73Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 343.74169921875,
                height: 23.0,
                child: GeneratedIfyoudonthaveanaccountSignuphereWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 26.0,
                child: GeneratedEnterUnsernameWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedEnterpasswordWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget13(),
              )
            ]),
      ),
    ));
  }
}
