import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedSearchWidget71.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedRectangle11Widget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedU1Widget25.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedHWidget54.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedNavWidget35.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedU1Widget24.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedU1Widget22.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedU1Widget23.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedEllipse2Widget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedsearchwidget69/generated/GeneratedHWidget53.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget69 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget53(),
              ),
              Positioned(
                left: 16.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 91.0,
                child: GeneratedRectangle11Widget12(),
              ),
              Positioned(
                left: 16.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 86.0,
                child: GeneratedU1Widget22(),
              ),
              Positioned(
                left: 215.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 86.0,
                child: GeneratedU1Widget23(),
              ),
              Positioned(
                left: 16.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 86.0,
                child: GeneratedU1Widget24(),
              ),
              Positioned(
                left: 198.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 86.0,
                child: GeneratedU1Widget25(),
              ),
              Positioned(
                left: 46.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 30.0,
                child: GeneratedHWidget54(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget35(),
              ),
              Positioned(
                left: 365.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedSearchWidget71(),
              ),
              Positioned(
                left: 127.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget44(),
              )
            ]),
      ),
    ));
  }
}
