import 'package:flutter/material.dart';

/* Rectangle Rectangle 680
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle680Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 818.0,
      height: 715.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          color: Color.fromARGB(255, 167, 167, 167),
        ),
      ),
    ));
  }
}
