import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedFrame26Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedContactinadminWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedArrowleftWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedBgWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroup487Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedIfyouarebeingbulliedoruseesomethingunappropriatewithint.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedFrame24Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroupBioEtherealUtaisanactivetightknitcommunityfilledwi.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedCreated23062022Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroup489Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedInterestWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroup65Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedLight1Widget56.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroupRulesMembershavetofollowtheruleswithinthegroupBefr.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedRectangle403Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedGroup276Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedFrame25Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity2joinwidget/generated/GeneratedRectangle491Widget57.dart';

/* Frame Community-2 ( join)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCommunity2joinWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 239, 239, 239),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 192.0,
              child: GeneratedRectangle403Widget1(),
            ),
            Positioned(
              left: 1.0,
              top: 320.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 1.0,
              child: GeneratedLine5Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 129.0,
              child: GeneratedBgWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget56(),
            ),
            Positioned(
              left: 25.0,
              top: 75.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrowleftWidget12(),
            ),
            Positioned(
              left: 388.0,
              top: 75.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedGroup65Widget7(),
            ),
            Positioned(
              left: 152.0,
              top: 915.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget57(),
            ),
            Positioned(
              left: 34.0,
              top: 407.0,
              right: null,
              bottom: null,
              width: 363.0,
              height: 107.0,
              child:
                  GeneratedGroupBioEtherealUtaisanactivetightknitcommunityfilledwi(),
            ),
            Positioned(
              left: 34.0,
              top: 524.0,
              right: null,
              bottom: null,
              width: 363.0,
              height: 214.0,
              child:
                  GeneratedGroupRulesMembershavetofollowtheruleswithinthegroupBefr(),
            ),
            Positioned(
              left: 108.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 59.0,
              height: 25.0,
              child: GeneratedFrame26Widget(),
            ),
            Positioned(
              left: 177.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 25.0,
              child: GeneratedGroup276Widget(),
            ),
            Positioned(
              left: 225.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 25.0,
              child: GeneratedFrame25Widget(),
            ),
            Positioned(
              left: 34.0,
              top: 372.0,
              right: null,
              bottom: null,
              width: 162.0,
              height: 25.0,
              child: GeneratedCreated23062022Widget(),
            ),
            Positioned(
              left: 34.0,
              top: 337.0,
              right: null,
              bottom: null,
              width: 68.0,
              height: 25.0,
              child: GeneratedInterestWidget(),
            ),
            Positioned(
              left: 305.0,
              top: 335.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 25.0,
              child: GeneratedFrame24Widget(),
            ),
            Positioned(
              left: 72.0,
              top: 854.0,
              right: null,
              bottom: null,
              width: 284.0,
              height: 49.0,
              child: GeneratedGroup489Widget(),
            ),
            Positioned(
              left: 34.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 125.0,
              height: 23.0,
              child: GeneratedContactinadminWidget(),
            ),
            Positioned(
              left: 34.0,
              top: 780.0,
              right: null,
              bottom: null,
              width: 363.0,
              height: 65.0,
              child:
                  GeneratedIfyouarebeingbulliedoruseesomethingunappropriatewithint(),
            ),
            Positioned(
              left: 125.0,
              top: 58.0,
              right: null,
              bottom: null,
              width: 178.0,
              height: 57.0,
              child: GeneratedGroup487Widget(),
            )
          ]),
    ));
  }
}
