import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe499widget/generated/GeneratedRectangle535Widget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe499widget/generated/Generated1825Widget1.dart';

/* Frame Frame 499
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame499Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIdentifyWidget'),
      child: Container(
        width: 388.0,
        height: 59.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget44(),
              ),
              Positioned(
                left: 169.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 32.0,
                child: Generated1825Widget1(),
              )
            ]),
      ),
    ));
  }
}
