import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedChooseyourusertypeWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedGroup299Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedAlreadyhaveanaccountLoginWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedGroup301Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedGroup404Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedEnterUsernameWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedGroup485Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedLight1Widget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedCreateyourpasswordWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedWelcometotheHealWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedGroup302Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedCREATEYOURACCOUNTWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedEnterpasswordWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedRectangle491Widget15.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedSelectyourUserTypeWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget/generated/GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget1.dart';

/* Frame Sign up-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget34(),
              ),
              Positioned(
                left: 20.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 50.0,
                child: GeneratedCREATEYOURACCOUNTWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 38.0,
                child: GeneratedWelcometotheHealWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 35.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 32.0,
                child: GeneratedCreateyourpasswordWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 32.0,
                child: GeneratedChooseyourusertypeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup301Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup299Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup302Widget2(),
              ),
              Positioned(
                left: 82.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 26.0,
                child: GeneratedAlreadyhaveanaccountLoginWidget2(),
              ),
              Positioned(
                left: 93.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 38.0,
                child:
                    GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget14(),
              ),
              Positioned(
                left: 20.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup404Widget5(),
              ),
              Positioned(
                left: 40.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 26.0,
                child: GeneratedSelectyourUserTypeWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 26.0,
                child: GeneratedEnterUsernameWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedEnterpasswordWidget1(),
              ),
              Positioned(
                left: 374.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 17.0,
                child: GeneratedGroup485Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget15(),
              )
            ]),
      ),
    ));
  }
}
