import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle8Widget23.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedEllipse2Widget24.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget70.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget66.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget73.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget65.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget69.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget67.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedHWidget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget68.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget71.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedFrameWidget149.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedFrameWidget148.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedFrameWidget150.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget72.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedNavWidget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedTitleWidget64.dart';
import 'package:flutterapp/thoughtspotapp/generatedtherapistwidget21/generated/GeneratedRectangle26Widget.dart';

/* Frame Therapist
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTherapistWidget21 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 172.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 172.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 172.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 34.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 34.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 34.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget34(),
              ),
              Positioned(
                left: 244.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 110.0,
                child: GeneratedRectangle8Widget23(),
              ),
              Positioned(
                left: 244.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 110.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 110.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 30.0,
                child: GeneratedTitleWidget64(),
              ),
              Positioned(
                left: 65.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 23.0,
                child: GeneratedTitleWidget65(),
              ),
              Positioned(
                left: 32.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 30.0,
                child: GeneratedTitleWidget66(),
              ),
              Positioned(
                left: 32.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 30.0,
                child: GeneratedTitleWidget67(),
              ),
              Positioned(
                left: 276.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedTitleWidget68(),
              ),
              Positioned(
                left: 276.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedTitleWidget69(),
              ),
              Positioned(
                left: 276.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedTitleWidget70(),
              ),
              Positioned(
                left: 32.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 94.0,
                child: GeneratedTitleWidget71(),
              ),
              Positioned(
                left: 32.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 94.0,
                child: GeneratedTitleWidget72(),
              ),
              Positioned(
                left: 32.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 94.0,
                child: GeneratedTitleWidget73(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget20(),
              ),
              Positioned(
                left: 286.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget24(),
              ),
              Positioned(
                left: 32.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 21.0,
                child: GeneratedFrameWidget148(),
              ),
              Positioned(
                left: 32.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 21.0,
                child: GeneratedFrameWidget149(),
              ),
              Positioned(
                left: 32.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 21.0,
                child: GeneratedFrameWidget150(),
              )
            ]),
      ),
    ));
  }
}
