import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedopenscreenwidget1/generated/GeneratedGroup484Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedopenscreenwidget1/generated/GeneratedRectangle491Widget65.dart';

/* Frame Open screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpenscreenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedOnboardingscreen1Widget1'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 926.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 255, 255, 255),
                                ),
                              ),
                              Positioned(
                                left: 27.0,
                                top: 209.0,
                                right: null,
                                bottom: null,
                                width: 374.0,
                                height: 451.0,
                                child: GeneratedGroup484Widget1(),
                              ),
                              Positioned(
                                left: 152.0,
                                top: 915.0,
                                right: null,
                                bottom: null,
                                width: 124.0,
                                height: 5.0,
                                child: GeneratedRectangle491Widget65(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
