import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedExperience6yearsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedJune15th2022Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedVectorWidget279.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedStatusAvailableWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedRectangle491Widget49.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedRectangle535Widget83.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedDuration1hourWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedRectangle94Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedAge35yearsoldWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedContinueWidget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedPhDinPsychologyWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedDrZhongAngelaWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedRectangle86Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/Generated8am9amMMTWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedLight1Widget47.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedPrice5000ksWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedRectangle95Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedLanguageEnglishChineseKoreanWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedBookasessionWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedMastersdegreeincounselingWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts8widget/generated/GeneratedClinicalPyschologistWidget5.dart';

/* Frame experts-8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget47(),
              ),
              Positioned(
                left: 98.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 38.0,
                child: Generated8am9amMMTWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 50.0,
                child: GeneratedJune15th2022Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget83(),
              ),
              Positioned(
                left: 172.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 32.0,
                child: GeneratedContinueWidget11(),
              ),
              Positioned(
                left: 121.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 185.0,
                child: GeneratedRectangle86Widget5(),
              ),
              Positioned(
                left: 124.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 38.0,
                child: GeneratedBookasessionWidget7(),
              ),
              Positioned(
                left: 31.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedVectorWidget279(),
              ),
              Positioned(
                left: 110.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 38.0,
                child: GeneratedDrZhongAngelaWidget6(),
              ),
              Positioned(
                left: 136.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 25.0,
                child: GeneratedClinicalPyschologistWidget5(),
              ),
              Positioned(
                left: 45.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 26.0,
                child: GeneratedLanguageEnglishChineseKoreanWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: GeneratedPrice5000ksWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedStatusAvailableWidget1(),
              ),
              Positioned(
                left: 46.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 26.0,
                child: GeneratedDuration1hourWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedAge35yearsoldWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 26.0,
                child: GeneratedExperience6yearsWidget1(),
              ),
              Positioned(
                left: 71.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 52.0,
                child: GeneratedRectangle94Widget1(),
              ),
              Positioned(
                left: 120.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 45.0,
                child: GeneratedRectangle95Widget1(),
              ),
              Positioned(
                left: 87.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 28.0,
                child: GeneratedMastersdegreeincounselingWidget1(),
              ),
              Positioned(
                left: 140.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 26.0,
                child: GeneratedPhDinPsychologyWidget1(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget49(),
              )
            ]),
      ),
    ));
  }
}
