import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedEllipse2Widget30.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedNavWidget24.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedECWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedTitleWidget104.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedJWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedTitleWidget103.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedGroup5Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedTitleWidget106.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedHWidget38.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwatchwidget2/generated/GeneratedTitleWidget105.dart';

/* Frame Watch
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWatchWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 862.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 732.0,
                child: GeneratedJWidget12(),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 44.0,
                child: GeneratedHWidget38(),
              ),
              Positioned(
                left: 16.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 198.0,
                child: GeneratedTitleWidget103(),
              ),
              Positioned(
                left: 209.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 33.0,
                child: GeneratedTitleWidget104(),
              ),
              Positioned(
                left: 209.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 21.0,
                child: GeneratedTitleWidget105(),
              ),
              Positioned(
                left: 209.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 61.0,
                child: GeneratedTitleWidget106(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget24(),
              ),
              Positioned(
                left: 361.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget30(),
              ),
              Positioned(
                left: 16.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 167.0,
                child: GeneratedRectangle18Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 104.0,
                child: GeneratedGroup5Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 319.5,
                height: 260.0,
                child: GeneratedECWidget4(),
              ),
              Positioned(
                left: 107.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedImage3Widget1(),
              )
            ]),
      ),
    ));
  }
}
