import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle546Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedFrame43Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedGroup209Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedLine25Widget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedLine24Widget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedGroup207Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle545Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedEllipse77Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedButtonWidget40.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedEllipse76Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedButtonWidget38.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedGroup206Widget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedGroup12Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedMavbarWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle543Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedLight1Widget74.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedEllipse78Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedBeccaWatsonWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedHelperWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle491Widget73.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedButtonWidget36.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedOurHelpersWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedLight2Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedHelperWidget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedHelperWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle544Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle549Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedBeccaWatsonWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedEllipse75Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedBeccaWatsonWidget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle548Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedHelperWidget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedGroup208Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedButtonWidget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedBeccaWatsonWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedAllWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedHelpersWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle547Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget1/generated/GeneratedRectangle550Widget2.dart';

/* Frame experts-1 (helpers)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts1helpersWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedLight1Widget74(),
                            ),
                            Positioned(
                              left: -146.0,
                              top: -1055.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedLight2Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 126.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 52.0,
                              child: GeneratedGroup206Widget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 78.0,
                              child: GeneratedMavbarWidget12(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 50.0,
                              child: GeneratedOurHelpersWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 129.0,
                              child: GeneratedRectangle543Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 265.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedRectangle544Widget4(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse75Widget2(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 265.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 29.0,
                              child: GeneratedBeccaWatsonWidget2(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 29.0,
                              child: GeneratedHelperWidget5(),
                            ),
                            Positioned(
                              left: 286.0,
                              top: 317.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 48.0,
                              child: GeneratedButtonWidget34(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup12Widget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 392.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 129.0,
                              child: GeneratedRectangle545Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedRectangle546Widget3(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse76Widget3(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 29.0,
                              child: GeneratedBeccaWatsonWidget3(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 29.0,
                              child: GeneratedHelperWidget6(),
                            ),
                            Positioned(
                              left: 286.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 48.0,
                              child: GeneratedButtonWidget36(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 471.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup207Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 538.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 129.0,
                              child: GeneratedRectangle547Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 557.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedRectangle548Widget3(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse77Widget1(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 557.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 29.0,
                              child: GeneratedBeccaWatsonWidget4(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 29.0,
                              child: GeneratedHelperWidget7(),
                            ),
                            Positioned(
                              left: 286.0,
                              top: 609.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 48.0,
                              child: GeneratedButtonWidget38(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup208Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 129.0,
                              child: GeneratedRectangle549Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 703.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedRectangle550Widget2(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 698.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse78Widget1(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 703.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 29.0,
                              child: GeneratedBeccaWatsonWidget5(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 29.0,
                              child: GeneratedHelperWidget8(),
                            ),
                            Positioned(
                              left: 286.0,
                              top: 755.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 48.0,
                              child: GeneratedButtonWidget40(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 763.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup209Widget2(),
                            ),
                            Positioned(
                              left: 205.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 29.0,
                              child: GeneratedAllWidget3(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 29.0,
                              child: GeneratedHelpersWidget3(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 24.0,
                              child: GeneratedFrame43Widget1(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 1.0,
                              child: GeneratedLine24Widget10(),
                            ),
                            Positioned(
                              left: 269.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 1.0,
                              child: GeneratedLine25Widget9(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 5.0,
                              child: GeneratedRectangle491Widget73(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
