import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedGroup424Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedYouhaventreceivedanynewsatthemomentWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedGroup417Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedNotificationsWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedGroup482Widget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedLine22Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedGroup416Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/Generated3Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedLight1Widget62.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedNonotificationsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhomenotiwidget/generated/GeneratedRectangle490Widget2.dart';

/* Frame Home/ noti
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomenotiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget62(),
              ),
              Positioned(
                left: 385.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 14.0,
                child: Generated3Widget5(),
              ),
              Positioned(
                left: 146.0,
                top: 914.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 6.0,
                child: GeneratedRectangle490Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 946.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 214.0,
                child: GeneratedGroup416Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 1180.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 214.0,
                child: GeneratedGroup417Widget1(),
              ),
              Positioned(
                left: 136.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 32.0,
                child: GeneratedNonotificationsWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 23.0,
                child: GeneratedYouhaventreceivedanynewsatthemomentWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 41.0,
                child: GeneratedNotificationsWidget3(),
              ),
              Positioned(
                left: -5.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 438.0,
                height: 1.0,
                child: GeneratedLine22Widget4(),
              ),
              Positioned(
                left: 169.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 92.71110534667969,
                height: 101.12752532958984,
                child: GeneratedGroup424Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 29.0,
                child: GeneratedGroup482Widget9(),
              )
            ]),
      ),
    ));
  }
}
