import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedColorsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedCaption1211Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedTypographyWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedLogo64Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedColourpaletteWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedPoppinsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedButton151618Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedTitle120Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedBody18Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedSubheading24Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedHeader32Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedtypographywidget/generated/GeneratedBody14Widget.dart';

/* Frame typography
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTypographyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 48.0,
              top: 246.0,
              right: null,
              bottom: null,
              width: 193.0,
              height: 50.0,
              child: GeneratedHeader32Widget(),
            ),
            Positioned(
              left: 48.0,
              top: 191.0,
              right: null,
              bottom: null,
              width: 168.0,
              height: 45.0,
              child: GeneratedLogo64Widget(),
            ),
            Positioned(
              left: 50.0,
              top: 306.0,
              right: null,
              bottom: null,
              width: 220.0,
              height: 38.0,
              child: GeneratedSubheading24Widget(),
            ),
            Positioned(
              left: 50.0,
              top: 354.0,
              right: null,
              bottom: null,
              width: 103.0,
              height: 32.0,
              child: GeneratedTitle120Widget(),
            ),
            Positioned(
              left: 50.0,
              top: 396.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 29.0,
              child: GeneratedBody18Widget(),
            ),
            Positioned(
              left: 48.0,
              top: 468.0,
              right: null,
              bottom: null,
              width: 68.0,
              height: 23.0,
              child: GeneratedBody14Widget(),
            ),
            Positioned(
              left: 48.0,
              top: 435.0,
              right: null,
              bottom: null,
              width: 121.0,
              height: 23.0,
              child: GeneratedButton151618Widget(),
            ),
            Positioned(
              left: 48.0,
              top: 501.0,
              right: null,
              bottom: null,
              width: 94.0,
              height: 20.0,
              child: GeneratedCaption1211Widget(),
            ),
            Positioned(
              left: 50.0,
              top: 131.0,
              right: null,
              bottom: null,
              width: 136.0,
              height: 53.0,
              child: GeneratedPoppinsWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 46.0,
              right: null,
              bottom: null,
              width: 204.0,
              height: 53.0,
              child: GeneratedTypographyWidget1(),
            ),
            Positioned(
              left: 643.0,
              top: 46.0,
              right: null,
              bottom: null,
              width: 110.0,
              height: 53.0,
              child: GeneratedColorsWidget(),
            ),
            Positioned(
              left: 456.0,
              top: 147.0,
              right: null,
              bottom: null,
              width: 478.0000305175781,
              height: 318.6666564941406,
              child: GeneratedColourpaletteWidget(),
            )
          ]),
    ));
  }
}
