import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedGroup404Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedVentyourfeelingsfreelyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedLight1Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedGroup298Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedGroup338Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedVectorWidget18.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedGroup299Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedRectangle491Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen1widget/generated/GeneratedEverexperiencedthetimewhenyouwantedtoventyourfeelingsto.dart';

/* Frame onboarding screen-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingscreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget18(),
              ),
              Positioned(
                left: 36.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 38.0,
                child: GeneratedVentyourfeelingsfreelyWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 122.0,
                child:
                    GeneratedEverexperiencedthetimewhenyouwantedtoventyourfeelingsto(),
              ),
              Positioned(
                left: 10.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 409.0,
                height: 291.0,
                child: GeneratedGroup299Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 59.0,
                child: GeneratedGroup298Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget5(),
              ),
              Positioned(
                left: 164.0,
                top: 792.2903442382812,
                right: null,
                bottom: null,
                width: 99.29032135009766,
                height: 10.290352821350098,
                child: GeneratedGroup338Widget(),
              ),
              Positioned(
                left: 345.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 32.0,
                child: GeneratedGroup404Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget6(),
              )
            ]),
      ),
    ));
  }
}
