import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/Generated1100AMWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedGroup343Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle535Widget82.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedContinueWidget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedGroup87Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedEveningWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle491Widget48.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/Generated1200PMWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle339Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle342Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/Generated1000AMWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle343Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedChoosearegionWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedSelectthetimezoneWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/Generated0700AMWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedMorningWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedBookasessionWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedRectangle344Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedGroup387Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedVectorWidget278.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedLight1Widget46.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts7widget/generated/GeneratedTherecanbeaslightlydifferentschedulingtimedependingonth.dart';

/* Frame experts-7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget46(),
              ),
              Positioned(
                left: 22.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 38.0,
                child: GeneratedSelectthetimezoneWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 389.0,
                height: 48.0,
                child:
                    GeneratedTherecanbeaslightlydifferentschedulingtimedependingonth(),
              ),
              Positioned(
                left: 21.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 46.0,
                child: GeneratedGroup87Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 53.0,
                child: GeneratedMorningWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 53.0,
                child: GeneratedEveningWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 46.0,
                child: GeneratedRectangle339Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 46.0,
                child: GeneratedRectangle342Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 46.0,
                child: GeneratedRectangle344Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 46.0,
                child: GeneratedRectangle343Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 24.0,
                child: Generated0700AMWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 24.0,
                child: Generated1000AMWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 24.0,
                child: Generated1100AMWidget(),
              ),
              Positioned(
                left: 313.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 24.0,
                child: Generated1200PMWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 46.0,
                child: GeneratedGroup387Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 46.0,
                child: GeneratedGroup343Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 23.0,
                child: GeneratedChoosearegionWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget82(),
              ),
              Positioned(
                left: 172.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 32.0,
                child: GeneratedContinueWidget10(),
              ),
              Positioned(
                left: 124.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 38.0,
                child: GeneratedBookasessionWidget6(),
              ),
              Positioned(
                left: 31.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedVectorWidget278(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget48(),
              )
            ]),
      ),
    ));
  }
}
