import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedpausewidget/generated/GeneratedRect3765Widget.dart';

/* Instance pause
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPauseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(50.0),
      child: Container(
        width: 36.0,
        height: 36.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(50.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(50.0),
                child: Container(
                  color: Color.fromARGB(255, 31, 64, 184),
                ),
              ),
              Positioned(
                left: 0.003348281141370535,
                top: 0.00336456298828125,
                right: null,
                bottom: null,
                width: 35.993309020996094,
                height: 35.99327087402344,
                child: GeneratedRect3765Widget(),
              )
            ]),
      ),
    ));
  }
}
