import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedopenscreenwidget/generated/GeneratedRectangle491Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedopenscreenwidget/generated/GeneratedGroup484Widget.dart';

/* Frame Open screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpenscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedOnboardingscreen1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 428.0,
          height: 926.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 27.0,
                  top: 209.0,
                  right: null,
                  bottom: null,
                  width: 374.0,
                  height: 451.0,
                  child: GeneratedGroup484Widget(),
                ),
                Positioned(
                  left: 152.0,
                  top: 915.0,
                  right: null,
                  bottom: null,
                  width: 124.0,
                  height: 5.0,
                  child: GeneratedRectangle491Widget5(),
                )
              ]),
        ),
      ),
    ));
  }
}
