import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedRectangle535Widget64.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedGroup405Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedSelectyourUserTypeWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedGroup479Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedGroup481Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedFrame62Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe497widget/generated/GeneratedGroup480Widget3.dart';

/* Frame Frame 497
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame497Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 388.0,
      height: 204.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 34.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 170.0,
              child: GeneratedRectangle535Widget64(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 59.0,
              child: GeneratedGroup405Widget4(),
            ),
            Positioned(
              left: 353.94775390625,
              top: 25.904296875,
              right: null,
              bottom: null,
              width: 15.143607139587402,
              height: 8.506194114685059,
              child: GeneratedFrame62Widget3(),
            ),
            Positioned(
              left: 20.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 173.0,
              height: 26.0,
              child: GeneratedSelectyourUserTypeWidget4(),
            ),
            Positioned(
              left: 7.0,
              top: 72.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup479Widget3(),
            ),
            Positioned(
              left: 7.0,
              top: 115.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup480Widget3(),
            ),
            Positioned(
              left: 7.0,
              top: 158.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup481Widget3(),
            )
          ]),
    ));
  }
}
