import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe493widget/generated/GeneratedGroup431Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe493widget/generated/GeneratedArtsWidget.dart';

/* Frame Frame 493
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame493Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 2497.0,
                height: 3907.0,
                child: GeneratedArtsWidget(),
              ),
              Positioned(
                left: 23.996795654296875,
                top: 96.0,
                right: null,
                bottom: null,
                width: 2368.1298828125,
                height: 3714.0,
                child: GeneratedGroup431Widget(),
              )
            ]),
      ),
    ));
  }
}
