import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedCharmtickWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedGroup396Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedEllipse76Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserChatWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedEllipse72Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedChatWidget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedRectangle491Widget51.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedGroup206Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedMavbarWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUnreadWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedFavouritesWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedRectangle380Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedEllipse75Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserChatWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedRectangle379Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserChatWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserNameWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedCharmtickWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserNameWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedLine25Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedAllWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserChatWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedGroup301Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedUserChatWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedLine24Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedEllipse71Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedGroup397Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchatwidget7/generated/GeneratedLight1Widget49.dart';

/* Frame chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget49(),
              ),
              Positioned(
                left: 28.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 123.0,
                child: GeneratedRectangle379Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 123.0,
                child: GeneratedRectangle380Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedEllipse71Widget1(),
              ),
              Positioned(
                left: 46.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedEllipse72Widget1(),
              ),
              Positioned(
                left: 160.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 178.5396270751953,
                height: 32.0,
                child: GeneratedUserNameWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 178.5396270751953,
                height: 32.0,
                child: GeneratedUserNameWidget1(),
              ),
              Positioned(
                left: 334.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedUserChatWidget(),
              ),
              Positioned(
                left: 334.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedUserChatWidget1(),
              ),
              Positioned(
                left: 118.0,
                top: 812.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 20.0,
                child: GeneratedUserChatWidget2(),
              ),
              Positioned(
                left: 160.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 25.0,
                child: GeneratedUserChatWidget3(),
              ),
              Positioned(
                left: 160.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 25.0,
                child: GeneratedUserChatWidget4(),
              ),
              Positioned(
                left: 113.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse75Widget1(),
              ),
              Positioned(
                left: 113.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse76Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 78.0,
                child: GeneratedMavbarWidget3(),
              ),
              Positioned(
                left: 174.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 53.0,
                child: GeneratedChatWidget10(),
              ),
              Positioned(
                left: 359.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 43.0,
                child: GeneratedGroup301Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 52.0,
                child: GeneratedGroup206Widget7(),
              ),
              Positioned(
                left: 193.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 29.0,
                child: GeneratedAllWidget2(),
              ),
              Positioned(
                left: 287.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 29.0,
                child: GeneratedFavouritesWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 29.0,
                child: GeneratedUnreadWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine24Widget8(),
              ),
              Positioned(
                left: 257.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine25Widget8(),
              ),
              Positioned(
                left: 317.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedCharmtickWidget(),
              ),
              Positioned(
                left: 317.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedCharmtickWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 123.0,
                child: GeneratedGroup396Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 123.0,
                child: GeneratedGroup397Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget51(),
              )
            ]),
      ),
    ));
  }
}
