import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedGroup405Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedLight1Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedConnectandchatwithourexpertsorhelperswhowouldmatchwithy.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedGroup404Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedChatWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedGroup338Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedGroup298Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedGroup299Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen2widget/generated/GeneratedRectangle491Widget7.dart';

/* Frame Onboarding screen-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingscreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget20(),
              ),
              Positioned(
                left: 36.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 98.0,
                child:
                    GeneratedConnectandchatwithourexpertsorhelperswhowouldmatchwithy(),
              ),
              Positioned(
                left: 36.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 41.0,
                child: GeneratedChatWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget6(),
              ),
              Positioned(
                left: 88.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 59.0,
                child: GeneratedGroup298Widget1(),
              ),
              Positioned(
                left: 88.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 59.0,
                child: GeneratedGroup405Widget(),
              ),
              Positioned(
                left: 345.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 32.0,
                child: GeneratedGroup404Widget1(),
              ),
              Positioned(
                left: 164.0,
                top: 792.2903442382812,
                right: null,
                bottom: null,
                width: 99.29032135009766,
                height: 10.290352821350098,
                child: GeneratedGroup338Widget1(),
              ),
              Positioned(
                left: 41.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 347.9407653808594,
                height: 359.0,
                child: GeneratedGroup299Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget7(),
              )
            ]),
      ),
    ));
  }
}
