import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle94Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedVectorWidget258.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedExperience6yearsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedPhDinPsychologyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedOurExpertsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle98Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedStatusAvailableWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle491Widget39.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle85Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedMastersdegreeincounselingWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle96Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedLanguageEnglishChineseKoreanWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle95Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedAge35yearsoldWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle535Widget74.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedDuration1hourWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedVectorWidget257.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedLight1Widget38.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedPrice5000ksWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedDrZhongAngelaWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedClinicalPyschologistWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedMoreinfoWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts2widget/generated/GeneratedRectangle86Widget.dart';

/* Frame experts-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget38(),
              ),
              Positioned(
                left: 121.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 50.0,
                child: GeneratedOurExpertsWidget1(),
              ),
              Positioned(
                left: -6.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 952.0,
                child: GeneratedRectangle98Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 771.0,
                child: GeneratedRectangle85Widget(),
              ),
              Positioned(
                left: 144.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 156.0,
                child: GeneratedRectangle86Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 38.0,
                child: GeneratedDrZhongAngelaWidget1(),
              ),
              Positioned(
                left: 136.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 25.0,
                child: GeneratedClinicalPyschologistWidget1(),
              ),
              Positioned(
                left: 122.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 183.9058837890625,
                height: 18.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 52.0,
                child: GeneratedRectangle94Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 52.0,
                child: GeneratedRectangle95Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 28.0,
                child: GeneratedMastersdegreeincounselingWidget(),
              ),
              Positioned(
                left: 136.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 29.0,
                child: GeneratedPhDinPsychologyWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 218.0,
                child: GeneratedRectangle96Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedVectorWidget257(),
              ),
              Positioned(
                left: 399.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedVectorWidget258(),
              ),
              Positioned(
                left: 352.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 26.0,
                child: GeneratedLanguageEnglishChineseKoreanWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: GeneratedPrice5000ksWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedStatusAvailableWidget(),
              ),
              Positioned(
                left: 69.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 26.0,
                child: GeneratedDuration1hourWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedAge35yearsoldWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 26.0,
                child: GeneratedExperience6yearsWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 59.0,
                child: GeneratedRectangle535Widget74(),
              ),
              Positioned(
                left: 172.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 29.0,
                child: GeneratedMoreinfoWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget39(),
              )
            ]),
      ),
    ));
  }
}
