import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedGroup486Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedFrame67Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedRectangle491Widget64.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedRectangle431Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedRectangle432Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedLine2Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedAngerisaverynormalhumanfeelingandcanbeapositiveemotionw1.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedRectangle528Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedGroup411Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedAngerAggressionWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticleswidget5/generated/GeneratedLight1Widget66.dart';

/* Frame Articles 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlesWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget66(),
              ),
              Positioned(
                left: 94.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 38.0,
                child: GeneratedAngerAggressionWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 431.00115966796875,
                height: 1.0,
                child: GeneratedLine2Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 521.0,
                child: GeneratedRectangle528Widget2(),
              ),
              Positioned(
                left: 29.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 463.0,
                child:
                    GeneratedAngerisaverynormalhumanfeelingandcanbeapositiveemotionw1(),
              ),
              Positioned(
                left: 20.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 7.0,
                child: GeneratedRectangle431Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 7.0,
                child: GeneratedRectangle432Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 59.0,
                child: GeneratedGroup411Widget1(),
              ),
              Positioned(
                left: 133.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 36.0,
                child: GeneratedGroup486Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget64(),
              ),
              Positioned(
                left: 17.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrame67Widget(),
              )
            ]),
      ),
    ));
  }
}
