import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedGroup306Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedFrame508Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedAlreadyhaveanaccountLoginWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedRectangle491Widget17.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedHOWDOYOUIDENTIFYWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedFrame517Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedGroup303Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedGroup305Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedFrame514Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedLight1Widget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedGroup304Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedFrame515Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedKnowingthiswillhelpussupportyouandyourneedsbetterWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedGroup302Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedidentifywidget/generated/GeneratedFrame516Widget.dart';

/* Frame Identify
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIdentifyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget37(),
              ),
              Positioned(
                left: 27.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 50.0,
                child: GeneratedHOWDOYOUIDENTIFYWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup302Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup303Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup304Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup305Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup306Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 26.0,
                child: GeneratedAlreadyhaveanaccountLoginWidget4(),
              ),
              Positioned(
                left: 93.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 38.0,
                child:
                    GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget16(),
              ),
              Positioned(
                left: 50.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 62.0,
                child:
                    GeneratedKnowingthiswillhelpussupportyouandyourneedsbetterWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedFrame508Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedFrame514Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedFrame515Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedFrame516Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedFrame517Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget17(),
              )
            ]),
      ),
    ));
  }
}
