import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedRectangle545Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedLast28daysWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedMoodstressandotherinsightsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedGroup228Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedInsightsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedGroup229Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedRectangle491Widget36.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedLine21Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedYouredoingwellContinuenurturingyourwellbeingtoexperienc.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedButtonWidget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedLight1Widget35.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedGroup482Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedMoodtimelineWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedMonthlyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedGroup393Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedOverallstresslevelsinthisperiodWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedOverallyouhavebeenfeelingokinthisperiodWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsinsightswidget/generated/GeneratedRectangle648Widget.dart';

/* Frame your goals- insights
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourgoalsinsightsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget35(),
            ),
            Positioned(
              left: 108.0,
              top: 184.0,
              right: null,
              bottom: null,
              width: 92.0,
              height: 48.0,
              child: GeneratedButtonWidget12(),
            ),
            Positioned(
              left: 228.0,
              top: 184.0,
              right: null,
              bottom: null,
              width: 92.0,
              height: 48.0,
              child: GeneratedButtonWidget14(),
            ),
            Positioned(
              left: 177.0,
              top: 279.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 32.0,
              child: GeneratedMonthlyWidget(),
            ),
            Positioned(
              left: 180.0,
              top: 314.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 19.0,
              child: GeneratedLast28daysWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 363.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 149.0,
              child: GeneratedRectangle545Widget(),
            ),
            Positioned(
              left: 174.0,
              top: 387.0,
              right: null,
              bottom: null,
              width: 215.0,
              height: 44.0,
              child: GeneratedOverallyouhavebeenfeelingokinthisperiodWidget(),
            ),
            Positioned(
              left: 174.0,
              top: 437.0,
              right: null,
              bottom: null,
              width: 204.0,
              height: 53.0,
              child:
                  GeneratedYouredoingwellContinuenurturingyourwellbeingtoexperienc(),
            ),
            Positioned(
              left: 28.0,
              top: 544.0,
              right: null,
              bottom: null,
              width: 148.0,
              height: 32.0,
              child: GeneratedMoodtimelineWidget(),
            ),
            Positioned(
              left: 28.0,
              top: 582.0,
              right: null,
              bottom: null,
              width: 269.0,
              height: 26.0,
              child: GeneratedOverallstresslevelsinthisperiodWidget(),
            ),
            Positioned(
              left: 31.0,
              top: 631.0,
              right: null,
              bottom: null,
              width: 366.0,
              height: 240.0,
              child: GeneratedGroup393Widget(),
            ),
            Positioned(
              left: 166.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 102.0,
              height: 41.0,
              child: GeneratedInsightsWidget1(),
            ),
            Positioned(
              left: 78.0,
              top: 281.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedGroup228Widget(),
            ),
            Positioned(
              left: 349.99658203125,
              top: 305.3984375,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedGroup229Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 130.0,
              right: null,
              bottom: null,
              width: 320.0,
              height: 32.0,
              child: GeneratedMoodstressandotherinsightsWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 1.0,
              child: GeneratedLine21Widget6(),
            ),
            Positioned(
              left: 152.0,
              top: 915.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget36(),
            ),
            Positioned(
              left: 43.0,
              top: 340.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 166.0,
              child: GeneratedRectangle648Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 59.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 29.0,
              child: GeneratedGroup482Widget7(),
            )
          ]),
    ));
  }
}
