import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedOurExpertsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedVectorWidget222.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedEllipse19Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedVectorWidget220.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/Generated5yearsExperienceWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedLine25Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedDrMariaLassgnaWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedLine24Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedDrZhongAngelaWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedPsychotheraphistWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/Generated4yearsExperienceWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedExpertsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedDrAlexMurphyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedFrame44Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedRectangle491Widget37.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedVectorWidget221.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedGroup206Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedClinicalPyschologistWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedAllWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedDrInakiGodughWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/Generated8yearsExperienceWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedRectangle70Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedFrame42Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/Generated3yearsExperienceWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedPsychotheraphistWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedMavbarWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedLight2Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedPsychologistWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1expertswidget/generated/GeneratedLight1Widget36.dart';

/* Frame experts-1 (experts)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts1expertsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget36(),
              ),
              Positioned(
                left: -146.0,
                top: -1055.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 131.0,
                child: GeneratedRectangle64Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 131.0,
                child: GeneratedRectangle66Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 131.0,
                child: GeneratedRectangle68Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 131.0,
                child: GeneratedRectangle70Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse19Widget3(),
              ),
              Positioned(
                left: 34.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse20Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse21Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse22Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 29.0,
                child: GeneratedDrZhongAngelaWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 29.0,
                child: GeneratedDrInakiGodughWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 29.0,
                child: GeneratedDrMariaLassgnaWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 29.0,
                child: GeneratedDrAlexMurphyWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 30.0,
                child: GeneratedClinicalPyschologistWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 29.0,
                child: GeneratedPsychologistWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 29.0,
                child: GeneratedPsychotheraphistWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 29.0,
                child: GeneratedPsychotheraphistWidget1(),
              ),
              Positioned(
                left: 156.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 20.0,
                child: Generated5yearsExperienceWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 20.0,
                child: Generated8yearsExperienceWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 20.0,
                child: Generated4yearsExperienceWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 20.0,
                child: Generated3yearsExperienceWidget(),
              ),
              Positioned(
                left: 375.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 8.25,
                height: 16.5,
                child: GeneratedFrame44Widget(),
              ),
              Positioned(
                left: 375.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 8.25,
                height: 16.5,
                child: GeneratedVectorWidget220(),
              ),
              Positioned(
                left: 375.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 8.25,
                height: 16.5,
                child: GeneratedVectorWidget221(),
              ),
              Positioned(
                left: 375.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 8.25,
                height: 16.5,
                child: GeneratedVectorWidget222(),
              ),
              Positioned(
                left: 156.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 50.0,
                child: GeneratedOurExpertsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 52.0,
                child: GeneratedGroup206Widget5(),
              ),
              Positioned(
                left: 205.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 29.0,
                child: GeneratedAllWidget(),
              ),
              Positioned(
                left: 302.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedFrame42Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 29.0,
                child: GeneratedExpertsWidget1(),
              ),
              Positioned(
                left: 160.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine24Widget6(),
              ),
              Positioned(
                left: 269.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine25Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 848.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 78.0,
                child: GeneratedMavbarWidget1(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget37(),
              )
            ]),
      ),
    ));
  }
}
