import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedGroup404Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedGroup299Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedGroup338Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedRectangle491Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedGroup298Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedBookasessionWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedIfyouneedprofessionalhelpyoucanbookasessionwithourcerti.dart';
import 'package:flutterapp/thoughtspotapp/generatedonboardingscreen3widget/generated/GeneratedLight1Widget7.dart';

/* Frame Onboarding screen-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardingscreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget22(),
              ),
              Positioned(
                left: 36.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 122.0,
                child:
                    GeneratedIfyouneedprofessionalhelpyoucanbookasessionwithourcerti(),
              ),
              Positioned(
                left: 36.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 38.0,
                child: GeneratedBookasessionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget7(),
              ),
              Positioned(
                left: 88.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 59.0,
                child: GeneratedGroup298Widget2(),
              ),
              Positioned(
                left: 338.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 32.0,
                child: GeneratedGroup404Widget2(),
              ),
              Positioned(
                left: 164.0,
                top: 792.2903442382812,
                right: null,
                bottom: null,
                width: 99.29032135009766,
                height: 10.290352821350098,
                child: GeneratedGroup338Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 385.1383361816406,
                height: 293.0,
                child: GeneratedGroup299Widget2(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget8(),
              )
            ]),
      ),
    ));
  }
}
