import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedRectangle641Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedRectangle645Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedEllipse95Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedTodaySedutperspiciatisomnisistenatuserrorsitvoluptatema7.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedUserChatWidget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedUserChatWidget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedArrowleftWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedIseeLetmeknowabouteverythingthatisbotheringyouWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedHiDanielHowiseverythingWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedLight1Widget50.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedEllipse97Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedGroup65Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedEllipse94Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedUserChatWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedUserChatWidget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedCharmtickdoubleWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedRectangle643Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedGroup370Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedCharmtickdoubleWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedGroup369Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedRectangle642Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedUserNameWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedEllipse69Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedGroup231Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedRectangle640Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedHiIhavebeenfeelingverydownlatelyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1widget/generated/GeneratedTodayWidget2.dart';

/* Frame chat- 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget50(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget7(),
              ),
              Positioned(
                left: 122.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 38.0,
                child: GeneratedUserNameWidget4(),
              ),
              Positioned(
                left: -14.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 463.0,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 281.0,
                child: GeneratedGroup231Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 64.0,
                child: GeneratedGroup369Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedEllipse69Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedEllipse95Widget1(),
              ),
              Positioned(
                left: 353.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedEllipse94Widget(),
              ),
              Positioned(
                left: 353.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedEllipse97Widget(),
              ),
              Positioned(
                left: 386.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup65Widget4(),
              ),
              Positioned(
                left: 53.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedGroup370Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 55.0,
                child: GeneratedRectangle640Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 63.0,
                child: GeneratedRectangle642Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 63.0,
                child: GeneratedRectangle641Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 140.0,
                child: GeneratedRectangle643Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 44.0,
                child: GeneratedHiDanielHowiseverythingWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 44.0,
                child: GeneratedHiIhavebeenfeelingverydownlatelyWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 128.0,
                child:
                    GeneratedTodaySedutperspiciatisomnisistenatuserrorsitvoluptatema7(),
              ),
              Positioned(
                left: 101.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 44.0,
                child:
                    GeneratedIseeLetmeknowabouteverythingthatisbotheringyouWidget(),
              ),
              Positioned(
                left: 270.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 20.0,
                child: GeneratedUserChatWidget9(),
              ),
              Positioned(
                left: 344.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 20.0,
                child: GeneratedUserChatWidget10(),
              ),
              Positioned(
                left: 114.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 20.0,
                child: GeneratedUserChatWidget11(),
              ),
              Positioned(
                left: 33.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 20.0,
                child: GeneratedUserChatWidget12(),
              ),
              Positioned(
                left: 94.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCharmtickdoubleWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCharmtickdoubleWidget1(),
              ),
              Positioned(
                left: 176.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 36.0,
                child: GeneratedRectangle645Widget1(),
              ),
              Positioned(
                left: 189.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 29.0,
                child: GeneratedTodayWidget2(),
              )
            ]),
      ),
    ));
  }
}
