import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe510widget/generated/GeneratedEngineerWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe510widget/generated/GeneratedRectangle535Widget54.dart';

/* Frame Frame 510
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame510Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomescreenWidget'),
      child: Container(
        width: 388.0,
        height: 59.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget54(),
              ),
              Positioned(
                left: 154.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedEngineerWidget1(),
              )
            ]),
      ),
    ));
  }
}
