import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle330Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedTreatmentFocusWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedLight1Widget40.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedGroup12Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle241Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle491Widget41.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedFrame81Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle535Widget76.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedChildAdolescentsYouthWorkingprofessionalsGeriatricsSeni.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedEllipse93Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedBookasessionWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedGroup173Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedApproachWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedClinicalPyschologistWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedGroup174Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedExpertsWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle491Widget42.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedRectangle86Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedDrZhongAngelaWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts4widget/generated/GeneratedGroup65Widget1.dart';

/* Frame experts-4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 213, 234, 240),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget76(),
              ),
              Positioned(
                left: 147.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 29.0,
                child: GeneratedBookasessionWidget2(),
              ),
              Positioned(
                left: -134.0,
                top: -355.0,
                right: null,
                bottom: null,
                width: 697.0,
                height: 697.0,
                child: GeneratedEllipse93Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget40(),
              ),
              Positioned(
                left: 31.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedFrame81Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 41.0,
                child: GeneratedExpertsWidget6(),
              ),
              Positioned(
                left: 386.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup65Widget1(),
              ),
              Positioned(
                left: 141.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 23.0,
                child: GeneratedClinicalPyschologistWidget3(),
              ),
              Positioned(
                left: 122.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 183.9058837890625,
                height: 18.0,
                child: GeneratedGroup12Widget3(),
              ),
              Positioned(
                left: 292.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedRectangle241Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedGroup174Widget1(),
              ),
              Positioned(
                left: 312.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 28.0,
                child: GeneratedApproachWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 48.0,
                child: GeneratedGroup173Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 360.0,
                child: GeneratedRectangle330Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedRectangle86Widget2(),
              ),
              Positioned(
                left: 112.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 38.0,
                child: GeneratedDrZhongAngelaWidget3(),
              ),
              Positioned(
                left: 36.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 235.0,
                child:
                    GeneratedChildAdolescentsYouthWorkingprofessionalsGeriatricsSeni(),
              ),
              Positioned(
                left: 40.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 29.0,
                child: GeneratedTreatmentFocusWidget(),
              ),
              Positioned(
                left: 3124.0,
                top: -3174.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget41(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget42(),
              )
            ]),
      ),
    ));
  }
}
