import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedGroup206Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedCoursesWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedLight1Widget25.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedRectangle491Widget26.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedFrame36Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedGroup251Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedeventswidget/generated/GeneratedGroup482Widget2.dart';

/* Frame Events
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget25(),
            ),
            Positioned(
              left: 164.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 105.0,
              height: 41.0,
              child: GeneratedCoursesWidget2(),
            ),
            Positioned(
              left: 20.0,
              top: 240.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 686.0,
              child: GeneratedFrame36Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 114.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 52.0,
              child: GeneratedGroup206Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 59.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 29.0,
              child: GeneratedGroup482Widget2(),
            ),
            Positioned(
              left: 51.0,
              top: 190.0,
              right: null,
              bottom: null,
              width: 306.0,
              height: 28.0,
              child: GeneratedGroup251Widget2(),
            ),
            Positioned(
              left: 152.0,
              top: 915.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget26(),
            )
          ]),
    ));
  }
}
