import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedBubblegumdone1Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedLight1Widget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedRectangle535Widget80.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedContinueWidget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedYoursessionhasbeenbookedWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedPaymentSuccessfulWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedTransactionhistoryWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts10widget/generated/GeneratedRectangle491Widget46.dart';

/* Frame Experts-10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget44(),
              ),
              Positioned(
                left: 128.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 29.0,
                child: GeneratedTransactionhistoryWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget80(),
              ),
              Positioned(
                left: 172.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 32.0,
                child: GeneratedContinueWidget9(),
              ),
              Positioned(
                left: 43.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 50.0,
                child: GeneratedPaymentSuccessfulWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 32.0,
                child: GeneratedYoursessionhasbeenbookedWidget(),
              ),
              Positioned(
                left: -14.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 456.0,
                height: 456.0,
                child: GeneratedBubblegumdone1Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget46(),
              )
            ]),
      ),
    ));
  }
}
