import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle550Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedBeccaWatsonWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedButtonWidget18.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle547Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedMavbarWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedEllipse76Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedGroup208Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedGroup209Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedFrame43Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedHelpersWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedGroup206Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedEllipse75Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle548Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle544Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedOurHelpersWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedHelperWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedHelperWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle491Widget38.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedButtonWidget22.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedLight1Widget37.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedHelperWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedHelperWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedLine24Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedDanielRacliffeWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedEllipse77Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedLight2Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle545Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedEleanorPenaWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedArleneMcCoyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedGroup207Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedEllipse78Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedLine25Widget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedGroup12Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle546Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedButtonWidget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle543Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedRectangle549Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedButtonWidget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts1helperswidget/generated/GeneratedAllWidget1.dart';

/* Frame experts-1 (helpers)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts1helpersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget37(),
              ),
              Positioned(
                left: -146.0,
                top: -1055.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight2Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 52.0,
                child: GeneratedGroup206Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 848.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 78.0,
                child: GeneratedMavbarWidget2(),
              ),
              Positioned(
                left: 119.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 50.0,
                child: GeneratedOurHelpersWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 392.0,
                height: 131.0,
                child: GeneratedRectangle543Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 129.0,
                child: GeneratedRectangle545Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 129.0,
                child: GeneratedRectangle547Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 129.0,
                child: GeneratedRectangle549Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedRectangle544Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedRectangle546Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedRectangle548Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedRectangle550Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse75Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse76Widget1(),
              ),
              Positioned(
                left: 113.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse77Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse78Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 29.0,
                child: GeneratedBeccaWatsonWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 29.0,
                child: GeneratedDanielRacliffeWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 29.0,
                child: GeneratedArleneMcCoyWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 29.0,
                child: GeneratedEleanorPenaWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 29.0,
                child: GeneratedHelperWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 29.0,
                child: GeneratedHelperWidget1(),
              ),
              Positioned(
                left: 140.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 29.0,
                child: GeneratedHelperWidget2(),
              ),
              Positioned(
                left: 140.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 29.0,
                child: GeneratedHelperWidget3(),
              ),
              Positioned(
                left: 286.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 48.0,
                child: GeneratedButtonWidget16(),
              ),
              Positioned(
                left: 286.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 48.0,
                child: GeneratedButtonWidget18(),
              ),
              Positioned(
                left: 286.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 48.0,
                child: GeneratedButtonWidget20(),
              ),
              Positioned(
                left: 286.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 48.0,
                child: GeneratedButtonWidget22(),
              ),
              Positioned(
                left: 140.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup12Widget1(),
              ),
              Positioned(
                left: 140.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup207Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup208Widget1(),
              ),
              Positioned(
                left: 140.0,
                top: 769.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 15.0,
                child: GeneratedGroup209Widget1(),
              ),
              Positioned(
                left: 205.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 29.0,
                child: GeneratedAllWidget1(),
              ),
              Positioned(
                left: 302.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 29.0,
                child: GeneratedHelpersWidget1(),
              ),
              Positioned(
                left: 70.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: GeneratedFrame43Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine24Widget7(),
              ),
              Positioned(
                left: 269.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 1.0,
                child: GeneratedLine25Widget7(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget38(),
              )
            ]),
      ),
    ));
  }
}
