import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe498widget/generated/GeneratedRectangle535Widget43.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe498widget/generated/GeneratedLESSTHAN18Widget1.dart';

/* Frame Frame 498
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame498Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIdentifyWidget'),
      child: Container(
        width: 388.0,
        height: 59.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget43(),
              ),
              Positioned(
                left: 136.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 29.0,
                child: GeneratedLESSTHAN18Widget1(),
              )
            ]),
      ),
    ));
  }
}
