import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedRectangle533Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedForalearnerusertypewesimplyaskyoutoanswerourQAforconfir.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedRectangle534Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedThequestionsarejustmultiplechoiceandsomeofthemareoption.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedEllipse18Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedQuestions18Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/Generated1115yearsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedEllipse16Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedGroup394Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedEllipse17Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedMorethan15yearsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedGroup299Widget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedRectangle531Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/Generated610yearsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedHowlonghaveyoubeeninterestedinPsychologyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedVectorWidget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/Generated15yearsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedRectangle532Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedWeheardthatyouhadchosentheHelperusertypeWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedRectangle491Widget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedEllipse19Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignupusertypeask1widget/generated/GeneratedLight1Widget19.dart';

/* Frame sign up/ user type (ask)-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupusertypeask1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 428.0,
          height: 926.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -1121.0,
                  top: 9592.0,
                  right: null,
                  bottom: null,
                  width: 20.000886917114258,
                  height: 20.000301361083984,
                  child: GeneratedVectorWidget44(),
                ),
                Positioned(
                  left: 20.0,
                  top: 810.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 59.0,
                  child: GeneratedGroup299Widget8(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 428.0,
                  height: 44.0,
                  child: GeneratedLight1Widget19(),
                ),
                Positioned(
                  left: 21.0,
                  top: 111.0,
                  right: null,
                  bottom: null,
                  width: 389.0,
                  height: 74.0,
                  child:
                      GeneratedWeheardthatyouhadchosentheHelperusertypeWidget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 205.0,
                  right: null,
                  bottom: null,
                  width: 389.0,
                  height: 56.0,
                  child:
                      GeneratedForalearnerusertypewesimplyaskyoutoanswerourQAforconfir(),
                ),
                Positioned(
                  left: 20.0,
                  top: 414.0,
                  right: null,
                  bottom: null,
                  width: 145.0,
                  height: 32.0,
                  child: GeneratedQuestions18Widget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 281.0,
                  right: null,
                  bottom: null,
                  width: 389.0,
                  height: 98.0,
                  child:
                      GeneratedThequestionsarejustmultiplechoiceandsomeofthemareoption(),
                ),
                Positioned(
                  left: 19.0,
                  top: 460.0,
                  right: null,
                  bottom: null,
                  width: 390.0,
                  height: 56.0,
                  child:
                      GeneratedHowlonghaveyoubeeninterestedinPsychologyWidget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 530.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 47.0,
                  child: GeneratedRectangle531Widget2(),
                ),
                Positioned(
                  left: 19.0,
                  top: 662.0,
                  right: null,
                  bottom: null,
                  width: 389.0,
                  height: 47.0,
                  child: GeneratedRectangle533Widget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 596.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 47.0,
                  child: GeneratedRectangle532Widget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 728.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 47.0,
                  child: GeneratedRectangle534Widget2(),
                ),
                Positioned(
                  left: 40.0,
                  top: 542.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse16Widget2(),
                ),
                Positioned(
                  left: 39.0,
                  top: 674.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse18Widget2(),
                ),
                Positioned(
                  left: 40.0,
                  top: 608.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse17Widget2(),
                ),
                Positioned(
                  left: 40.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse19Widget2(),
                ),
                Positioned(
                  left: 93.0,
                  top: 542.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 26.0,
                  child: Generated15yearsWidget(),
                ),
                Positioned(
                  left: 93.0,
                  top: 674.0,
                  right: null,
                  bottom: null,
                  width: 85.0,
                  height: 26.0,
                  child: Generated1115yearsWidget(),
                ),
                Positioned(
                  left: 93.0,
                  top: 608.0,
                  right: null,
                  bottom: null,
                  width: 85.0,
                  height: 26.0,
                  child: Generated610yearsWidget(),
                ),
                Positioned(
                  left: 93.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 154.0,
                  height: 26.0,
                  child: GeneratedMorethan15yearsWidget(),
                ),
                Positioned(
                  left: 12.0,
                  top: 62.0,
                  right: null,
                  bottom: null,
                  width: 84.0,
                  height: 32.0,
                  child: GeneratedGroup394Widget1(),
                ),
                Positioned(
                  left: 152.0,
                  top: 915.0,
                  right: null,
                  bottom: null,
                  width: 124.0,
                  height: 5.0,
                  child: GeneratedRectangle491Widget20(),
                )
              ]),
        ),
      ),
    ));
  }
}
