import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedHiWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedEllipse2Widget42.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedRectangle7Widget15.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedTitle4Widget24.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedGroup3Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedTitle2Widget66.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedNavWidget33.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedReactionWidget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedFrame1Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedTitle3Widget56.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedFrame2Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedQuoteWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedReactionWidget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedHWidget49.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedReactionafterWidget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedr2widget2/generated/GeneratedTitleWidget125.dart';

/* Frame R2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedR2Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 44.0,
                child: GeneratedHWidget49(),
              ),
              Positioned(
                left: 16.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget125(),
              ),
              Positioned(
                left: 16.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 112.0,
                child: GeneratedRectangle7Widget15(),
              ),
              Positioned(
                left: 16.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitle2Widget66(),
              ),
              Positioned(
                left: 16.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 33.0,
                child: GeneratedTitle3Widget56(),
              ),
              Positioned(
                left: 16.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitle4Widget24(),
              ),
              Positioned(
                left: 16.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 398.0,
                height: 112.0,
                child: GeneratedFrame1Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 398.0,
                height: 112.0,
                child: GeneratedFrame2Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 56.0,
                child: GeneratedQuoteWidget6(),
              ),
              Positioned(
                left: 293.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedHiWidget6(),
              ),
              Positioned(
                left: 65.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 60.0,
                child: GeneratedReactionWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget33(),
              ),
              Positioned(
                left: 49.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget42(),
              ),
              Positioned(
                left: 65.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 54.0,
                child: GeneratedReactionafterWidget10(),
              ),
              Positioned(
                left: 88.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 44.0,
                child: GeneratedReactionWidget12(),
              ),
              Positioned(
                left: 264.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 54.0,
                child: GeneratedGroup3Widget4(),
              )
            ]),
      ),
    ));
  }
}
