import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedFa6brandsfacebooksquareWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedOrsignupwithWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedRectangle491Widget12.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedGroup300Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedGroup301Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedEnteryouremailWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedGroup298Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedGroup345Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedEnteremailWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedWhatsyouremailWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedGroup299Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedLight1Widget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup1widget/generated/GeneratedFrame74Widget.dart';

/* Frame Sign up-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget29(),
              ),
              Positioned(
                left: 20.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 50.0,
                child: GeneratedEnteryouremailWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 38.0,
                child: GeneratedOrsignupwithWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 32.0,
                child: GeneratedWhatsyouremailWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup298Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup299Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup300Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup301Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup345Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedFa6brandsfacebooksquareWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget11(),
              ),
              Positioned(
                left: 82.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 24.0,
                child: GeneratedFrame74Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 26.0,
                child: GeneratedEnteremailWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 44.0,
                child:
                    GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget12(),
              )
            ]),
      ),
    ));
  }
}
