import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedGroup482Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedGroup206Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedAllRecordsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedYourRecordsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedRecycleBinWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedLine25Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedFavouriteWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedLine21Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedLight1Widget31.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedLine24Widget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/Generated3Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedRectangle491Widget32.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsmyrecords2widget/generated/GeneratedMYRECORDSWidget1.dart';

/* Frame your goals- my records 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourgoalsmyrecords2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 385.0,
              top: 57.0,
              right: null,
              bottom: null,
              width: 10.0,
              height: 14.0,
              child: Generated3Widget3(),
            ),
            Positioned(
              left: 134.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 163.0,
              height: 38.0,
              child: GeneratedYourRecordsWidget1(),
            ),
            Positioned(
              left: -5.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 433.0,
              height: 1.0,
              child: GeneratedLine21Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 52.0,
              child: GeneratedGroup206Widget4(),
            ),
            Positioned(
              left: 20.0,
              top: 188.0,
              right: null,
              bottom: null,
              width: 207.0,
              height: 50.0,
              child: GeneratedMYRECORDSWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget31(),
            ),
            Positioned(
              left: 41.0,
              top: 249.0,
              right: null,
              bottom: null,
              width: 90.0,
              height: 26.0,
              child: GeneratedAllRecordsWidget1(),
            ),
            Positioned(
              left: 299.0,
              top: 249.0,
              right: null,
              bottom: null,
              width: 93.0,
              height: 26.0,
              child: GeneratedRecycleBinWidget1(),
            ),
            Positioned(
              left: 97.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 29.0,
              child: GeneratedFavouriteWidget1(),
            ),
            Positioned(
              left: 153.0,
              top: 247.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 1.0,
              child: GeneratedLine24Widget4(),
            ),
            Positioned(
              left: 275.0,
              top: 247.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 1.0,
              child: GeneratedLine25Widget4(),
            ),
            Positioned(
              left: 21.0,
              top: 295.0,
              right: null,
              bottom: null,
              width: 387.0,
              height: 629.0,
              child: GeneratedFrame35Widget(),
            ),
            Positioned(
              left: 152.0,
              top: 913.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget32(),
            ),
            Positioned(
              left: 20.0,
              top: 59.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 29.0,
              child: GeneratedGroup482Widget4(),
            )
          ]),
    ));
  }
}
