import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedLight1Widget63.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedRectangle491Widget61.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedGroup297Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedEllipse93Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedProfileWidget18.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedMavbarWidget8.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedFrame45Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedEllipse98Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourprofilewidget/generated/GeneratedEllipse94Widget6.dart';

/* Frame your profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -134.0,
                top: -386.0,
                right: null,
                bottom: null,
                width: 697.0,
                height: 697.0,
                child: GeneratedEllipse93Widget6(),
              ),
              Positioned(
                left: -134.0,
                top: -386.0,
                right: null,
                bottom: null,
                width: 697.0,
                height: 697.0,
                child: GeneratedEllipse98Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget63(),
              ),
              Positioned(
                left: 174.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 43.0,
                child: GeneratedProfileWidget18(),
              ),
              Positioned(
                left: 164.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse94Widget6(),
              ),
              Positioned(
                left: 149.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 96.0,
                child: GeneratedGroup297Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 389.0,
                height: 510.0,
                child: GeneratedFrame45Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 78.0,
                child: GeneratedMavbarWidget8(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget61(),
              )
            ]),
      ),
    ));
  }
}
