import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedGroup5Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedHWidget37.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedTitleWidget97.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedNavWidget23.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedJWidget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedTitleWidget94.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedTitleWidget95.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedEllipse2Widget28.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedTitleWidget96.dart';
import 'package:flutterapp/thoughtspotapp/generatedprofilewidget46/generated/GeneratedImage3Widget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget46 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 862.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 732.0,
                child: GeneratedJWidget11(),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 44.0,
                child: GeneratedHWidget37(),
              ),
              Positioned(
                left: 16.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 198.0,
                child: GeneratedTitleWidget94(),
              ),
              Positioned(
                left: 209.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 33.0,
                child: GeneratedTitleWidget95(),
              ),
              Positioned(
                left: 209.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 21.0,
                child: GeneratedTitleWidget96(),
              ),
              Positioned(
                left: 209.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 61.0,
                child: GeneratedTitleWidget97(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget23(),
              ),
              Positioned(
                left: 361.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget28(),
              ),
              Positioned(
                left: 16.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 167.0,
                child: GeneratedRectangle18Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 104.0,
                child: GeneratedGroup5Widget2(),
              ),
              Positioned(
                left: 317.899169921875,
                top: -187.7236328125,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 693.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse9Widget(),
              )
            ]),
      ),
    ));
  }
}
