import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedGreatjobDanielWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedYoureallsetAndnowyourereadytostartyourjourneyinHEALWidg1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedLight1Widget73.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedRectangle491Widget72.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedDidyoumakeamistakeGoBackWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedGroup299Widget18.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedCasuallife3dbluedoorwithsteps11Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedwelcomescreenwidget2/generated/GeneratedVectorWidget1378.dart';

/* Frame welcome screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomescreenWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 9612.000301361084,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1121.0,
                              top: 9592.0,
                              right: null,
                              bottom: null,
                              width: 20.000886917114258,
                              height: 20.000301361083984,
                              child: GeneratedVectorWidget1378(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 752.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 59.0,
                              child: GeneratedGroup299Widget18(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 283.0,
                              height: 50.0,
                              child: GeneratedGreatjobDanielWidget1(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 56.0,
                              child:
                                  GeneratedYoureallsetAndnowyourereadytostartyourjourneyinHEALWidg1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedLight1Widget73(),
                            ),
                            Positioned(
                              left: 135.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 354.0,
                              child:
                                  GeneratedCasuallife3dbluedoorwithsteps11Widget2(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 821.0,
                              right: null,
                              bottom: null,
                              width: 343.74169921875,
                              height: 26.0,
                              child: GeneratedDidyoumakeamistakeGoBackWidget1(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 5.0,
                              child: GeneratedRectangle491Widget72(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
