import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedCreateyourpasswordWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedGroup485Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedEnterpasswordWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedRectangle491Widget71.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedGroup404Widget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedAlreadyhaveanaccountLoginWidget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedEnterUsernameWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedChooseyourusertypeWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedGroup299Widget17.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedGroup302Widget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedLight1Widget72.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedVectorWidget1376.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedSelectyourUserTypeWidget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedCREATEYOURACCOUNTWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedUsernameWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedGroup301Widget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget7.dart';
import 'package:flutterapp/thoughtspotapp/generatedsignup2widget1/generated/GeneratedWelcometotheThoughtspotWidget.dart';

/* Frame Sign up-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignup2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 9612.000301361084,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1121.0,
                              top: 9592.0,
                              right: null,
                              bottom: null,
                              width: 20.000886917114258,
                              height: 20.000301361083984,
                              child: GeneratedVectorWidget1376(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 50.0,
                              child: GeneratedCREATEYOURACCOUNTWidget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 38.0,
                              child: GeneratedWelcometotheThoughtspotWidget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 213.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 35.0,
                              child: GeneratedUsernameWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 226.0,
                              height: 32.0,
                              child: GeneratedCreateyourpasswordWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 455.0,
                              right: null,
                              bottom: null,
                              width: 229.0,
                              height: 32.0,
                              child: GeneratedChooseyourusertypeWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 259.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 59.0,
                              child: GeneratedGroup301Widget9(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 59.0,
                              child: GeneratedGroup299Widget17(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 59.0,
                              child: GeneratedGroup302Widget11(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 805.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 26.0,
                              child:
                                  GeneratedAlreadyhaveanaccountLoginWidget9(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 38.0,
                              child:
                                  GeneratedBycreatinganaccontyouagreetoourPrivacyPolicyWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child: GeneratedLight1Widget72(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 501.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 59.0,
                              child: GeneratedGroup404Widget9(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 518.0,
                              right: null,
                              bottom: null,
                              width: 173.0,
                              height: 26.0,
                              child: GeneratedSelectyourUserTypeWidget5(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 276.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 26.0,
                              child: GeneratedEnterUsernameWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 398.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 26.0,
                              child: GeneratedEnterpasswordWidget3(),
                            ),
                            Positioned(
                              left: 374.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 17.0,
                              child: GeneratedGroup485Widget1(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 5.0,
                              child: GeneratedRectangle491Widget71(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
