import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedHealLogo0112Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedLight1Widget10.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedThoughtSpotWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedRectangle491Widget11.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedPrivacyPolicyWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedGroup299Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedGroup300Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedVectorWidget28.dart';
import 'package:flutterapp/thoughtspotapp/generatedintroscreenwidget/generated/GeneratedFrame82Widget.dart';

/* Frame intro screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1121.0,
                top: 9592.0,
                right: null,
                bottom: null,
                width: 20.000886917114258,
                height: 20.000301361083984,
                child: GeneratedVectorWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget10(),
              ),
              Positioned(
                left: 1.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 152.0,
                child: GeneratedThoughtSpotWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup299Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedGroup300Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 24.0,
                child: GeneratedFrame82Widget(),
              ),
              Positioned(
                left: 173.0,
                top: 812.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 20.0,
                child: GeneratedPrivacyPolicyWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 366.0,
                child: GeneratedHealLogo0112Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget11(),
              )
            ]),
      ),
    ));
  }
}
