import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedHeyDanielWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedArrow8Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedRectangle491Widget44.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedJuly2022Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedBookasessionWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedPleaseselecttheappointmentdateyouwouldliketoconsultwith.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedArrow7Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedFrame78Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedLight1Widget42.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedRectangle535Widget78.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedConfirmdateWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedexperts6widget/generated/GeneratedGroup442Widget.dart';

/* Frame experts-6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperts6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 254, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget42(),
              ),
              Positioned(
                left: 20.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 50.0,
                child: GeneratedHeyDanielWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 50.0,
                child:
                    GeneratedPleaseselecttheappointmentdateyouwouldliketoconsultwith(),
              ),
              Positioned(
                left: 170.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 24.0,
                child: GeneratedJuly2022Widget1(),
              ),
              Positioned(
                left: 137.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 0.0,
                child: GeneratedArrow7Widget(),
              ),
              Positioned(
                left: 291.0,
                top: 273.10009765625,
                right: null,
                bottom: null,
                width: 3.498584032058716,
                height: 0.09995953738689423,
                child: GeneratedArrow8Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 365.0,
                child: GeneratedGroup442Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 843.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget78(),
              ),
              Positioned(
                left: 147.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 29.0,
                child: GeneratedConfirmdateWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 38.0,
                child: GeneratedBookasessionWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 16.0,
                child: GeneratedFrame78Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget44(),
              )
            ]),
      ),
    ));
  }
}
