import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedRectangle491Widget35.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedGroup447Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedDailyTasksWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedGroup482Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedLight1Widget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedDizzymentalwellbeing1Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedLetscompletethetasksandgetrewardsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedGroup426Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalsdailytaskswidget/generated/GeneratedLine21Widget5.dart';

/* Frame your goals- daily tasks
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourgoalsdailytasksWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget34(),
            ),
            Positioned(
              left: 25.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 29.0,
              child: GeneratedLetscompletethetasksandgetrewardsWidget(),
            ),
            Positioned(
              left: 23.0,
              top: 424.0,
              right: null,
              bottom: null,
              width: 381.0,
              height: 377.0,
              child: GeneratedGroup447Widget(),
            ),
            Positioned(
              left: 145.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 140.0,
              height: 38.0,
              child: GeneratedDailyTasksWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 1.0,
              child: GeneratedLine21Widget5(),
            ),
            Positioned(
              left: 21.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 216.0,
              child: GeneratedDizzymentalwellbeing1Widget(),
            ),
            Positioned(
              left: 88.0,
              top: 834.0,
              right: null,
              bottom: null,
              width: 252.0,
              height: 59.0,
              child: GeneratedGroup426Widget(),
            ),
            Positioned(
              left: 152.0,
              top: 915.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget35(),
            ),
            Positioned(
              left: 20.0,
              top: 59.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 29.0,
              child: GeneratedGroup482Widget6(),
            )
          ]),
    ));
  }
}
