import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedDrZhongAngelaWidget19.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedClinicalPyschologistWidget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedFrame47Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedClinicalPyschologistWidget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/Generated5yearsExperienceWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroup210Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/Generated5yearsExperienceWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedEllipse26Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedRectangle497Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroup212Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedExpertsWidget26.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroupWidget60.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedClinicalPyschologistWidget15.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedDrZhongAngelaWidget18.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedDrZhongAngelaWidget16.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedMavbarWidget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedFrame46Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroup211Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedEllipse24Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedFrame45Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedAllWidget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedOurExpertsWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroup213Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedRectangle496Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/Generated5yearsExperienceWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedRectangle498Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedFrame49Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedRectangle499Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedFrame48Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedGroup214Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedRectangle492Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/Generated5yearsExperienceWidget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedDrZhongAngelaWidget17.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedwireboxexperts1expertswidget/generated/GeneratedClinicalPyschologistWidget17.dart';

/* Frame Wire Box / experts-1 (experts)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWireBoxexperts1expertsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1968.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 536.921875,
                              height: 1968.0,
                              child: GeneratedGroupWidget60(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 252.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 131.0,
                              child: GeneratedRectangle492Widget3(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 273.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedEllipse23Widget(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 29.0,
                              child: GeneratedDrZhongAngelaWidget16(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 298.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 30.0,
                              child: GeneratedClinicalPyschologistWidget14(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 326.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 20.0,
                              child: Generated5yearsExperienceWidget2(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 8.25,
                              height: 16.5,
                              child: GeneratedFrame45Widget2(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup210Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 398.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 131.0,
                              child: GeneratedRectangle497Widget3(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 419.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedEllipse24Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 414.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 29.0,
                              child: GeneratedDrZhongAngelaWidget17(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 444.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 30.0,
                              child: GeneratedClinicalPyschologistWidget15(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 20.0,
                              child: Generated5yearsExperienceWidget3(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 456.0,
                              right: null,
                              bottom: null,
                              width: 8.25,
                              height: 16.5,
                              child: GeneratedFrame47Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 498.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup212Widget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 542.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 131.0,
                              child: GeneratedRectangle498Widget3(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedEllipse25Widget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 29.0,
                              child: GeneratedDrZhongAngelaWidget18(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 30.0,
                              child: GeneratedClinicalPyschologistWidget16(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 20.0,
                              child: Generated5yearsExperienceWidget4(),
                            ),
                            Positioned(
                              left: 369.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 8.25,
                              height: 16.5,
                              child: GeneratedFrame48Widget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup213Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 688.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 131.0,
                              child: GeneratedRectangle499Widget3(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 89.0,
                              child: GeneratedEllipse26Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 704.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 29.0,
                              child: GeneratedDrZhongAngelaWidget19(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 30.0,
                              child: GeneratedClinicalPyschologistWidget17(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 762.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 20.0,
                              child: Generated5yearsExperienceWidget5(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 8.25,
                              height: 16.5,
                              child: GeneratedFrame49Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 788.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 15.0,
                              child: GeneratedGroup214Widget1(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 50.0,
                              child: GeneratedOurExpertsWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 126.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 52.0,
                              child: GeneratedGroup211Widget(),
                            ),
                            Positioned(
                              left: 205.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 29.0,
                              child: GeneratedAllWidget5(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 24.0,
                              child: GeneratedFrame46Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedExpertsWidget26(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 1.0,
                              child: GeneratedLine26Widget(),
                            ),
                            Positioned(
                              left: 269.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 1.0,
                              child: GeneratedLine27Widget(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 5.0,
                              child: GeneratedRectangle496Widget3(),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 78.0,
                              child: GeneratedMavbarWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
