import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget79.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget74.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget78.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedNavWidget21.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedGroup7Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget75.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget76.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedHWidget35.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedRectangle16Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedECWidget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget77.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedEllipse2Widget25.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedTitleWidget81.dart';
import 'package:flutterapp/thoughtspotapp/generatedemergencywidget1/generated/GeneratedRectangle8Widget24.dart';

/* Frame Emergency
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmergencyWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 244),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget35(),
              ),
              Positioned(
                left: 257.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 173.0,
                child: GeneratedRectangle8Widget24(),
              ),
              Positioned(
                left: 16.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget74(),
              ),
              Positioned(
                left: 16.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 30.0,
                child: GeneratedTitleWidget75(),
              ),
              Positioned(
                left: 16.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 33.0,
                child: GeneratedTitleWidget76(),
              ),
              Positioned(
                left: 16.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 86.0,
                child: GeneratedTitleWidget77(),
              ),
              Positioned(
                left: 16.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 37.0,
                child: GeneratedTitleWidget78(),
              ),
              Positioned(
                left: 16.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 72.0,
                child: GeneratedTitleWidget79(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget21(),
              ),
              Positioned(
                left: 286.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget25(),
              ),
              Positioned(
                left: 215.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 104.0,
                child: GeneratedRectangle16Widget5(),
              ),
              Positioned(
                left: 16.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 104.0,
                child: GeneratedGroup7Widget3(),
              ),
              Positioned(
                left: 259.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 33.0,
                child: GeneratedTitleWidget81(),
              ),
              Positioned(
                left: 55.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 192.0,
                child: GeneratedECWidget2(),
              )
            ]),
      ),
    ));
  }
}
