import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedRectangle535Widget62.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedGroup481Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedGroup479Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedGroup480Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedFrame62Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedSelectyourUserTypeWidget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe496widget/generated/GeneratedGroup405Widget3.dart';

/* Frame Frame 496
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame496Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 388.0,
      height: 204.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 34.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 170.0,
              child: GeneratedRectangle535Widget62(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 59.0,
              child: GeneratedGroup405Widget3(),
            ),
            Positioned(
              left: 353.94775390625,
              top: 25.904296875,
              right: null,
              bottom: null,
              width: 15.143607139587402,
              height: 8.506194114685059,
              child: GeneratedFrame62Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 173.0,
              height: 26.0,
              child: GeneratedSelectyourUserTypeWidget3(),
            ),
            Positioned(
              left: 7.0,
              top: 72.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup479Widget2(),
            ),
            Positioned(
              left: 7.0,
              top: 115.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup480Widget2(),
            ),
            Positioned(
              left: 7.0,
              top: 158.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 34.0,
              child: GeneratedGroup481Widget2(),
            )
          ]),
    ));
  }
}
