import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedEllipse2Widget37.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedRectangle14Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedFrameWidget173.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedTitle6Widget13.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedTitle7Widget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedFrame6Widget14.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedNavWidget28.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedTitle5Widget20.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunitywidget46/generated/GeneratedHWidget43.dart';

/* Frame Community
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCommunityWidget46 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 225, 225),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 652.0,
                child: GeneratedFrame6Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedNavWidget28(),
              ),
              Positioned(
                left: 207.0,
                top: 874.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedEllipse2Widget37(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 228.0,
                child: GeneratedRectangle14Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 47.0,
                child: GeneratedHWidget43(),
              ),
              Positioned(
                left: 16.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 55.0,
                child: GeneratedRectangle13Widget6(),
              ),
              Positioned(
                left: 42.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 30.0,
                child: GeneratedTitle5Widget20(),
              ),
              Positioned(
                left: 317.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 26.0,
                child: GeneratedTitle7Widget20(),
              ),
              Positioned(
                left: 358.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 33.0,
                child: GeneratedTitle6Widget13(),
              ),
              Positioned(
                left: 374.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget173(),
              )
            ]),
      ),
    ));
  }
}
