import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle491Widget30.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle432Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle528Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedLight1Widget29.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle431Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedBecauseofWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedGroup491Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedEnergeticWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedThursday141522ndJuly2022Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle527Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedTodayIfeltWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/Generated33Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedRectangle503Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogyourmood2widget/generated/GeneratedWorkenvironmentHealthStudyWidget.dart';

/* Frame your goals- log your mood 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourgoalslogyourmood2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget29(),
            ),
            Positioned(
              left: 20.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 7.0,
              child: GeneratedRectangle431Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 7.0,
              child: GeneratedRectangle432Widget2(),
            ),
            Positioned(
              left: 386.0,
              top: 75.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 22.0,
              child: Generated33Widget(),
            ),
            Positioned(
              left: 19.0,
              top: 199.0,
              right: null,
              bottom: null,
              width: 112.0,
              height: 29.0,
              child: GeneratedTodayIfeltWidget(),
            ),
            Positioned(
              left: 19.0,
              top: 465.0,
              right: null,
              bottom: null,
              width: 113.0,
              height: 29.0,
              child: GeneratedBecauseofWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 114.0,
              right: null,
              bottom: null,
              width: 181.0,
              height: 74.0,
              child: GeneratedThursday141522ndJuly2022Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 500.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 209.0,
              child: GeneratedRectangle527Widget1(),
            ),
            Positioned(
              left: 20.0,
              top: 234.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 209.0,
              child: GeneratedRectangle528Widget1(),
            ),
            Positioned(
              left: 125.0,
              top: 236.0,
              right: null,
              bottom: null,
              width: 178.0,
              height: 176.0,
              child: GeneratedRectangle503Widget1(),
            ),
            Positioned(
              left: 181.0,
              top: 412.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 28.0,
              child: GeneratedEnergeticWidget1(),
            ),
            Positioned(
              left: 40.0,
              top: 519.0,
              right: null,
              bottom: null,
              width: 149.0,
              height: 74.0,
              child: GeneratedWorkenvironmentHealthStudyWidget(),
            ),
            Positioned(
              left: 152.0,
              top: 914.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget30(),
            ),
            Positioned(
              left: 88.0,
              top: 834.0,
              right: null,
              bottom: null,
              width: 252.0,
              height: 59.0,
              child: GeneratedGroup491Widget(),
            )
          ]),
    ));
  }
}
