import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedArticlesWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup248Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedLight1Widget23.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup206Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup251Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup250Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedRectangle491Widget24.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup247Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedGroup249Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedarticlesandpodcasts1widget/generated/GeneratedFrame66Widget.dart';

/* Frame Articles and podcasts-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlesandpodcasts1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget23(),
              ),
              Positioned(
                left: 20.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrame66Widget(),
              ),
              Positioned(
                left: 169.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 41.0,
                child: GeneratedArticlesWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 52.0,
                child: GeneratedGroup206Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 28.0,
                child: GeneratedGroup251Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 153.0,
                child: GeneratedGroup250Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 153.0,
                child: GeneratedGroup247Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 153.0,
                child: GeneratedGroup248Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 153.0,
                child: GeneratedGroup249Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget24(),
              )
            ]),
      ),
    ));
  }
}
