import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedLine2Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedGroup364Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedRectangle544Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedGroup367Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedMicWidget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedPinnedmessagesWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedArrowleftWidget9.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedSnoozenotificationsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedUserNameWidget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedGroup365Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedBlockBeccaWatsonWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedDeleteconversationWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedImagesandVideosWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedChooseThemeWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedReportBeccaWatsonWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedLight1Widget52.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedBeccaWatsonWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedVoicemessagesWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedHelperWidget4.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedRectangle491Widget53.dart';
import 'package:flutterapp/thoughtspotapp/generatedchat1optionwidget/generated/GeneratedGroup229Widget1.dart';

/* Frame chat-1 (option)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat1optionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 384.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup367Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget52(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget9(),
              ),
              Positioned(
                left: 98.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 38.0,
                child: GeneratedUserNameWidget6(),
              ),
              Positioned(
                left: -8.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 1.0,
                child: GeneratedLine2Widget2(),
              ),
              Positioned(
                left: -8.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 449.0,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: -8.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 449.0,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 449.0,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 35.0,
                child: GeneratedNotificationsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 26.0,
                child: GeneratedSnoozenotificationsWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 26.0,
                child: GeneratedImagesandVideosWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 26.0,
                child: GeneratedPinnedmessagesWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 26.0,
                child: GeneratedVoicemessagesWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 115.0,
                child: GeneratedRectangle544Widget1(),
              ),
              Positioned(
                left: 148.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 29.0,
                child: GeneratedBeccaWatsonWidget1(),
              ),
              Positioned(
                left: 188.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 29.0,
                child: GeneratedHelperWidget4(),
              ),
              Positioned(
                left: 353.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 38.46154022216797,
                height: 20.0,
                child: GeneratedGroup229Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMicWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup365Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup364Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 26.0,
                child: GeneratedChooseThemeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 26.0,
                child: GeneratedReportBeccaWatsonWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 26.0,
                child: GeneratedBlockBeccaWatsonWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 26.0,
                child: GeneratedDeleteconversationWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget53(),
              )
            ]),
      ),
    ));
  }
}
