import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedLight1Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedEllipse19Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedDoyoufeelcapableofmakingdecisionsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedMoresothanusualWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedLesssothanusualWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedEllipse17Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle532Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedEllipse16Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle491Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedEllipse18Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle535Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle533Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle531Widget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedMuchlesscapableWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedGoodWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedhometest3widget/generated/GeneratedRectangle534Widget1.dart';

/* Frame Home/ test-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHometest3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 428.0,
          height: 926.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 428.0,
                  height: 44.0,
                  child: GeneratedLight1Widget3(),
                ),
                Positioned(
                  left: 20.0,
                  top: 62.0,
                  right: null,
                  bottom: null,
                  width: 94.0,
                  height: 30.0,
                  child: GeneratedGroup1Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 147.0,
                  right: null,
                  bottom: null,
                  width: 390.0,
                  height: 74.0,
                  child: GeneratedDoyoufeelcapableofmakingdecisionsWidget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 70.0,
                  child: GeneratedRectangle531Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 337.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 70.0,
                  child: GeneratedRectangle532Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 431.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 70.0,
                  child: GeneratedRectangle533Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 525.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 70.0,
                  child: GeneratedRectangle534Widget1(),
                ),
                Positioned(
                  left: 36.0,
                  top: 266.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse16Widget1(),
                ),
                Positioned(
                  left: 36.0,
                  top: 360.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse17Widget1(),
                ),
                Positioned(
                  left: 36.0,
                  top: 454.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse18Widget1(),
                ),
                Positioned(
                  left: 36.0,
                  top: 548.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEllipse19Widget1(),
                ),
                Positioned(
                  left: 101.0,
                  top: 263.0,
                  right: null,
                  bottom: null,
                  width: 192.0,
                  height: 32.0,
                  child: GeneratedMoresothanusualWidget(),
                ),
                Positioned(
                  left: 101.0,
                  top: 357.0,
                  right: null,
                  bottom: null,
                  width: 60.0,
                  height: 35.0,
                  child: GeneratedGoodWidget1(),
                ),
                Positioned(
                  left: 101.0,
                  top: 451.0,
                  right: null,
                  bottom: null,
                  width: 185.0,
                  height: 32.0,
                  child: GeneratedLesssothanusualWidget1(),
                ),
                Positioned(
                  left: 101.0,
                  top: 545.0,
                  right: null,
                  bottom: null,
                  width: 190.0,
                  height: 32.0,
                  child: GeneratedMuchlesscapableWidget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 825.0,
                  right: null,
                  bottom: null,
                  width: 388.0,
                  height: 59.0,
                  child: GeneratedRectangle535Widget1(),
                ),
                Positioned(
                  left: 181.0,
                  top: 841.0,
                  right: null,
                  bottom: null,
                  width: 71.0,
                  height: 32.0,
                  child: GeneratedSubmitWidget(),
                ),
                Positioned(
                  left: 152.0,
                  top: 915.0,
                  right: null,
                  bottom: null,
                  width: 124.0,
                  height: 5.0,
                  child: GeneratedRectangle491Widget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
