import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedGroup482Widget5.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedAaWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedGroup352Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/Generated1200am18June2022Wordcount45wordsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedTodaySedutperspiciatisomnisistenatuserrorsitvoluptatema6.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedLight1Widget33.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedGroup302Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedGroup303Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedMyCrushWidget1.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedGroup304Widget3.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedRectangle491Widget34.dart';
import 'package:flutterapp/thoughtspotapp/generatedyourgoalslogmyjournal1widget/generated/GeneratedLine21Widget4.dart';

/* Frame your goals- log my journal-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYourgoalslogmyjournal1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 926.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 44.0,
                child: GeneratedLight1Widget33(),
              ),
              Positioned(
                left: 20.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 41.0,
                child: GeneratedMyCrushWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 428.0000915527344,
                height: 234.14442443847656,
                child: GeneratedGroup352Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 915.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 5.0,
                child: GeneratedRectangle491Widget34(),
              ),
              Positioned(
                left: 19.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 389.0,
                height: 161.0,
                child:
                    GeneratedTodaySedutperspiciatisomnisistenatuserrorsitvoluptatema6(),
              ),
              Positioned(
                left: 0.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 1.0,
                child: GeneratedLine21Widget4(),
              ),
              Positioned(
                left: 19.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 66.0,
                child: Generated1200am18June2022Wordcount45wordsWidget(),
              ),
              Positioned(
                left: 378.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 44.0,
                child: GeneratedAaWidget(),
              ),
              Positioned(
                left: 299.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup302Widget6(),
              ),
              Positioned(
                left: 259.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup303Widget3(),
              ),
              Positioned(
                left: 339.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup304Widget3(),
              ),
              Positioned(
                left: 29.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 29.0,
                child: GeneratedGroup482Widget5(),
              )
            ]),
      ),
    ));
  }
}
