import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedEtherealUta30postsWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedLight1Widget55.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedFrame38Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedGroup65Widget6.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedRectangle491Widget56.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedRectangle403Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedGroup351Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedBgWidget.dart';
import 'package:flutterapp/thoughtspotapp/generatedcommunity3widget/generated/GeneratedArrowleftWidget11.dart';

/* Frame Community-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCommunity3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 926.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 239, 239, 239),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 192.0,
              child: GeneratedRectangle403Widget(),
            ),
            Positioned(
              left: 1.0,
              top: 320.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 1.0,
              child: GeneratedLine5Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 129.0,
              child: GeneratedBgWidget(),
            ),
            Positioned(
              left: 140.0,
              top: 55.0,
              right: null,
              bottom: null,
              width: 151.0,
              height: 56.0,
              child: GeneratedEtherealUta30postsWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 44.0,
              child: GeneratedLight1Widget55(),
            ),
            Positioned(
              left: 20.0,
              top: 391.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 529.0,
              child: GeneratedFrame38Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 851.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 51.0,
              child: GeneratedComponent4Widget(),
            ),
            Positioned(
              left: 357.0,
              top: 655.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 247.0,
              child: GeneratedComponent1Widget(),
            ),
            Positioned(
              left: 22.0,
              top: 68.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrowleftWidget11(),
            ),
            Positioned(
              left: 388.0,
              top: 68.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedGroup65Widget6(),
            ),
            Positioned(
              left: 152.0,
              top: 915.0,
              right: null,
              bottom: null,
              width: 124.0,
              height: 5.0,
              child: GeneratedRectangle491Widget56(),
            ),
            Positioned(
              left: 29.0,
              top: 345.0,
              right: null,
              bottom: null,
              width: 370.0,
              height: 25.0,
              child: GeneratedGroup351Widget(),
            )
          ]),
    ));
  }
}
