import 'package:flutter/material.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe506widget/generated/GeneratedRectangle535Widget51.dart';
import 'package:flutterapp/thoughtspotapp/generatedframe506widget/generated/GeneratedOthersWidget2.dart';

/* Frame Frame 506
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame506Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedProfessionWidget'),
      child: Container(
        width: 388.0,
        height: 59.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 59.0,
                child: GeneratedRectangle535Widget51(),
              ),
              Positioned(
                left: 163.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 32.0,
                child: GeneratedOthersWidget2(),
              )
            ]),
      ),
    ));
  }
}
